Frontend adjustments for Stripe refactoring
enso-org/enso pull request #10054
Opened 2024-05-23 13:38 UTC by MrFlashAccount

### Pull Request Description

#### Tl;dr 
Closes: enso-org/cloud-v2#1185
This PR changes endpoints according to the comment left by @PabloBuchu: https://github.com/enso-org/cloud-v2/issues/1185#issuecomment-2114606101

#### This Change:
Changes endpoint names and fixes subscription flow

---

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

2024-05-23 13:39 UTC, somebody1234 approved these changes

2024-05-27 12:48 UTC, PabloBuchu commented
Why I am having this in the console? Is it related to the PR?

<img width="1140" alt="Screenshot 2024-05-27 at 14 48 29" src="https://github.com/enso-org/enso/assets/2855109/29d55037-5c6a-46b8-8c24-e9ffe92203cc">

2024-05-27 12:56 UTC, MrFlashAccount commented
Not sure it's related to the PR, I guess it's the white list policy in the IDE. We need to adjust them to allow additional hosts: https://github.com/enso-org/enso/blob/d4ef04bc524f2866be2f77884d82a9d5d76cc1d4/app/ide-desktop/lib/client/src/security.ts#L96

2024-05-27 13:10 UTC, PabloBuchu commented
Small one but can we center the button?

<img width="796" alt="Screenshot 2024-05-27 at 15 10 18" src="https://github.com/enso-org/enso/assets/2855109/a432eea7-f947-40d4-9d5b-619197f670a4">

2024-05-27 13:19 UTC, PabloBuchu approved these changes

2024-05-27 13:20 UTC, MrFlashAccount commented
> Small one but can we center the button?

It's not small :) Fixed it

2024-05-27 13:42 UTC, PabloBuchu commented
Found one problematic bug. When I typed organization name already present in the system (names are globally unique) the modal is unresponsive. I can't change the input and resubmit nor close it

https://github.com/enso-org/enso/assets/2855109/97b8c41a-0a8d-4b17-b73f-de85a8cbbae5

2024-05-27 13:42 UTC, PabloBuchu requested changes
see comment with bug

2024-05-27 13:52 UTC, MrFlashAccount commented
Oh this is wild... will take a look

2024-05-27 13:53 UTC, MrFlashAccount commented
also, the error is stuck to the input above.

2024-05-28 08:47 UTC, MrFlashAccount commented
@PabloBuchu fixed

2024-05-30 07:37 UTC, MrFlashAccount commented on app/gui2/index.html
> +    <div id="enso-portal-root" class="enso-portal-root"></div>
We want to be sure that `.enso-portal-root` goes after the dashboard to stay on top of the whole app, so we put this element explicitly after the `dashboard` and `chat`

2024-05-30 11:35 UTC, Frizi approved these changes
Approving the index change in gui.

2024-05-31 09:33 UTC, PabloBuchu approved these changes

2024-05-31 09:59 UTC, merged