`--attach-debugger` to start LS with debugger
enso-org/enso pull request #10062
Opened 2024-05-23 20:06 UTC by hubertp

### Pull Request Description

This change adds a simple cli parameter to start Language Server with remote debugging capabilities. Whenever I needed to attach the debbugger a) I had to lookup the non-trivial `agentlib` options b) figure out where to add it and build the whole distribution again.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

2024-05-24 13:03 UTC, Akirathan approved these changes
Thanks for the QOL improvement. Consider my suggestion for better docs and naming, please.

2024-05-24 13:03 UTC, Akirathan commented on lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/RunSettings.scala
> +  * @param attachDebugger if true, indicates that the runner should be started with remote debugging capabilities
Let's make the docs a little bit more precise, pls. Starting something with debugging capabilities is very vague. Replace that with something like:
```suggestion
  * @param attachDebugger if true, indicates that the runner should be suspended until a debugger is attached.
```

Maybe even change the param name to `waitForDebugger`?

2024-05-27 07:18 UTC, JaroslavTulach requested changes
First of all: I am not sure we want to expose such an option to Enso users at all. It is only useful in the rare case Hubert is facing right now.

Second: If this option shall go in, then let's make consistent with `runProjectDistribution --debug`. However that one is using `server=n` - e.g. some more trickery around the new option may be needed.

2024-05-27 07:18 UTC, JaroslavTulach commented on lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
> +             "-agentlib:jdwp=transport=dt_socket,server=y,address=localhost:5005,suspend=y"
Is this the _non trivial_ option we are make this for? I do understand your pain, I feel it too every time I have to type `transport=dt_socket`, but...

2024-05-27 07:18 UTC, JaroslavTulach commented on lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/Cli.scala
> +      .desc("Enables remote debugging capabilities")
This isn't sufficient documentation for someone seeing output of `project-manager --help`.

2024-05-27 07:18 UTC, JaroslavTulach commented on lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/Cli.scala
> +  val ATTACH_DEBUGGER    = "attach-debugger"
Do we really believe _Enso users_ will benefit (ever use) this option?

2024-05-27 13:19 UTC, hubertp commented
@JaroslavTulach I can hide it from `--help` so that it doesn't show up there but still exists. Would that make you happy?

2024-05-27 21:12 UTC, hubertp commented
Alternatively, we could have Language Server specific `JVM_OPTS` like `LS_JVM_OPTS` that will be always passed around.

2024-05-28 09:07 UTC, JaroslavTulach commented
> Alternatively, we could have Language Server specific `JVM_OPTS` like `LS_JVM_OPTS` that will be always passed around.

There is Project Manager+Language Server specific API. It is called `ENSO_JVM_OPTS`. Documented in
- #3404 

Used in `runProjectManagerDistribution`: 
- https://github.com/enso-org/enso/blob/8f9fc0822c3de8faa67a15b669f139bf17c16723/lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala#L145
- https://github.com/enso-org/enso/blob/8f9fc0822c3de8faa67a15b669f139bf17c16723/project/DistributionPackage.scala#L313 

and elsewhere...

2024-05-29 20:32 UTC, hubertp commented
Fair enough, I somehow forgot about `ENSO_JVM_OPTS`

2024-05-29 20:32 UTC, closed without merging