Implement markdown link syntax and "follow link" popup.
enso-org/enso pull request #10353
Opened 2024-06-24 13:58 UTC by Frizi

### Pull Request Description

Fixes #9907

Implements link support in the comment markdown editor. Supports both markdown-style links and auto-detection for raw URLs.

https://github.com/enso-org/enso/assets/919491/b38f860a-ee4a-41a8-b936-41e9ef1602b9

https://github.com/enso-org/enso/assets/919491/059beca2-7737-41a1-a136-31a42ef9ee48

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

2024-06-24 17:18 UTC, kazcw requested changes
Some little things, and two blockers:
- This changes application bundling in a way that would negatively impact load time (details are in a review comment). The easiest solution would be to load the plain-text editor asynchronously, but it would be possible to keep it lightweight by separating the new logic needed by the PlainTextEditor from the rich text dependencies.
- Has link opening been tested in Electron?

2024-06-24 17:18 UTC, kazcw commented on app/gui2/src/components/MarkdownEditor/link.ts
> +      return true
I don't think this should stop propagation

2024-06-24 17:18 UTC, kazcw commented on app/gui2/src/components/PlainTextEditor.vue
> +import { useLinkNode } from '@/components/MarkdownEditor/link'
Lexical has a small core, and a collection of extensions for rich text support. Before this change, the bulk of Lexical dependencies are bundled with the markdown editor and loaded when it is needed. This bundling boundary corresponds to the `MarkdownEditor` directory. `PlainTextEditor` is not loaded asynchronously because its dependency closure has been minimal. Adding dependencies from `MarkdownEditor` to the `PlainTextEditor` would move a lot of bundled code from being lazily-loaded when needed to being required to start the application.

2024-06-24 17:18 UTC, kazcw commented on app/gui2/src/components/MarkdownEditor/LinkToolbar.vue
> +    <span class="shortcut">(ctrl + click)</span>
Cmd+click on Mac, and we usually capitalize `ctrl`. This could use the modifier pretty-printing logic from `shortcuts.ts`.

2024-06-24 17:18 UTC, kazcw commented on app/gui2/src/components/MarkdownEditor/LinkPlugin/index.ts
> +  /(?<!\()(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))/
This looks worth testing

2024-06-24 17:18 UTC, kazcw commented on app/gui2/src/components/MarkdownEditor/LinkPlugin/autoMatcher.ts
> +type LinkMatcherResult = {
I think `Result` in a type name is a bit loaded--I would expect this type to be the full outcome of link matching (whether a match occurred or not).

2024-06-24 17:18 UTC, kazcw commented on app/gui2/src/components/MarkdownEditor/LinkPlugin/autoMatcher.ts
> +    /*!previousSibling.getIsUnlinked() &&*/
Commented code

2024-06-24 17:18 UTC, kazcw commented on app/gui2/src/components/MarkdownEditor/LinkPlugin/autoMatcher.ts
> +    $isAutoLinkNode(nextSibling) /*&& !nextSibling.getIsUnlinked()*/ &&
Commented code

2024-06-24 17:18 UTC, kazcw commented on app/gui2/src/components/MarkdownEditor/LinkPlugin/autoMatcher.ts
> +            //   parent.setIsUnlinked(!parent.getIsUnlinked())
Commented code

2024-06-24 17:18 UTC, kazcw commented on app/gui2/src/components/MarkdownEditor/LinkPlugin/autoMatcher.ts
> +      if ($isAutoLinkNode(parent) /*&& !parent.getIsUnlinked() */) {
Commented code

2024-06-24 17:18 UTC, kazcw commented on app/gui2/src/components/MarkdownEditor/LinkPlugin/index.ts
> +            window.open(link.getURL(), '_blank')?.focus()
I think we need some Electron logic to handle window-open requests by launching an external browser

2024-06-25 10:00 UTC, Frizi commented on app/gui2/src/components/MarkdownEditor/LinkPlugin/autoMatcher.ts
> +    /*!previousSibling.getIsUnlinked() &&*/
On purpose, `IsUnlinked` is not yet supported in current version of lexical, but will be available in next release. Those commented fragments can then be uncommented for full "ignore link" behavior support.

2024-06-25 10:00 UTC, Frizi commented on app/gui2/src/components/MarkdownEditor/LinkPlugin/autoMatcher.ts
> +    $isAutoLinkNode(nextSibling) /*&& !nextSibling.getIsUnlinked()*/ &&
Same as above, expected to be uncommented after next lexical release.

2024-06-25 10:00 UTC, Frizi commented on app/gui2/src/components/MarkdownEditor/LinkPlugin/autoMatcher.ts
> +            //   parent.setIsUnlinked(!parent.getIsUnlinked())
Same as above, expected to be uncommented after next lexical release.

2024-06-25 10:00 UTC, Frizi commented on app/gui2/src/components/MarkdownEditor/LinkPlugin/autoMatcher.ts
> +      if ($isAutoLinkNode(parent) /*&& !parent.getIsUnlinked() */) {
Same as above, expected to be uncommented after next lexical release.

2024-06-25 11:05 UTC, somebody1234 approved these changes
Approving Electron security changes. Not too sure about removing `TRUSTED_EXTERNAL_HOSTS` but I suppose it's intentional...

2024-06-25 11:29 UTC, Frizi commented
Yeah, we are now supporting arbitrary linking intentionally, therefore `TRUSTED_EXTERNAL_HOSTS` doesn't make much sense anymore.

2024-06-25 13:27 UTC, kazcw approved these changes

2024-06-25 14:41 UTC, kazcw commented
The bundling issue was fixed by removing `PlainTextEditor`'s dependency on `MarkdownEditor/formatting.ts`.

2024-06-27 14:18 UTC, merged