Cloud file browser
enso-org/enso pull request #10513
Opened 2024-07-10 15:53 UTC by kazcw

### Pull Request Description

Demo will be included when my cloud account gets fixed...

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

2024-07-10 15:54 UTC, kazcw commented
Stacked on dashboard changes in #10442; IDE changes ready for review.

2024-07-10 15:56 UTC, somebody1234 commented on app/gui2/src/App.vue
> +import Backend from 'enso-common/src/services/Backend'
`import type`?

2024-07-10 16:05 UTC, somebody1234 approved these changes
approving dashboard changes. for posterity, here's the diff between this branch and its parent:
https://github.com/enso-org/enso/compare/wip/kw/cloud-files/2-backend..wip/kw/cloud-files/3-cloud-browser

2024-07-11 08:01 UTC, farmaazon requested changes
The code looks really nice

2024-07-11 08:01 UTC, farmaazon commented on app/gui2/src/components/FileBrowserWidget.vue
I think it would fit into `@/components/widgets` directory.

2024-07-11 08:01 UTC, farmaazon commented on app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
> +const activity = shallowRef<VNode>()
I would add a short comment with example of such activity, as for any new dev it might not be obvious (the cloud file browser may be not often seen).

2024-07-11 08:01 UTC, farmaazon commented on app/gui2/src/providers/backend.ts
> +    backend: computed(() => toValue(backend)),
Isn't `computed(() => toValue(...))` and equivalent of `toRef(...)`? I think toRef may omit some unnecessary wrapping.

2024-07-11 08:02 UTC, farmaazon approved these changes
I meant approval :)

2024-07-15 15:22 UTC, merged