Add --dump-irs cmdline option
enso-org/enso pull request #10740
Opened 2024-08-02 16:41 UTC by Akirathan

### Pull Request Description

Working on compiler IR is a daunting task. I have therefore added a new command line option `--dump-irs` that will help with that. It dumps the encountered IRs to `ir-dumps` directory in the [GraphViz](www.graphviz.org) format. More info in updated docs.

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

2024-08-03 04:15 UTC, JaroslavTulach requested changes
By adding option like that to default `enso` launcher, you are about to expose such a functionality to end users. Are we ready to support the option, the format, etc. to Enso customers? I doubt.

Replace this CLI option with `-Denso.xyz` to hide it.

When at it, also remove `--dump-graphs`. It was a mistake to add it.

2024-08-05 11:12 UTC, Akirathan commented
> Replace this CLI option with -Denso.xyz to hide it.

Good idea. It is now hidden in `enso.compiler.dumpIr` system prop, done in https://github.com/enso-org/enso/pull/10740/commits/35202149482fff11c5669e207e6f3b627e82298b.

> When at it, also remove --dump-graphs. It was a mistake to add it.

Removed in https://github.com/enso-org/enso/pull/10740/commits/7314efe1978715af4c752b600f629fa064393ea1.

2024-08-05 11:34 UTC, JaroslavTulach approved these changes

2024-08-06 11:25 UTC, radeusgd approved these changes

2024-08-06 12:00 UTC, merged