Fix component list scrolling
enso-org/enso pull request #10937
Opened 2024-08-30 13:43 UTC by vitvakatu

### Pull Request Description

Fixes https://github.com/enso-org/enso/issues/10927

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

2024-08-30 14:33 UTC, Frizi approved these changes
I'm not sure about this bugfix, the old code here seems to me actually correct. All it does is to select a range of elements to render baesd on scroller viewport, and I don't see any flaw in that logic. 

The issue seems to be that the `scrolling.scrollPosition` can actually lie - the reported "scroll position" is past the scroll height bounds. So my propsed fix would be to instead limit that value, something like this:

```ts
const scrolling = useScrolling(() =>
  Math.min(animatedHighlightPosition.value, listContentHeight.value - scrollerSize.value.y),
)
```

2024-08-30 14:33 UTC, Frizi requested changes
Sorry didn't mean to approve 🫨

2024-09-02 09:39 UTC, vitvakatu commented
Indeed, the proposed fix is easier and works perfectly fine.

2024-09-02 14:11 UTC, Frizi approved these changes

2024-09-02 17:09 UTC, merged