Run node in a different execution environment
enso-org/enso pull request #11173
Opened 2024-09-25 19:58 UTC by 4e6

### Pull Request Description

close #10719

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

2024-09-27 14:15 UTC, JaroslavTulach requested changes
Use [ContextThreadLocal](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/ContextThreadLocal.html).

2024-09-27 14:15 UTC, JaroslavTulach commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
> +  @TruffleBoundary
I don't think we want `@TruffleBoundary` here. Quite opposite. We want this to be fast!

2024-09-27 14:15 UTC, JaroslavTulach commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
> +  private final ThreadLocal<ExecutionEnvironment> threadExecutionEnvironment;
Don't use `ThreadLocal`, but Truffle's own [ContextThreadLocal](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/ContextThreadLocal.html).

2024-10-03 03:17 UTC, JaroslavTulach commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
> +  @TruffleBoundary
Can you remove the boundary, @4e6, or are there some problems that prevent it to be removed?

2024-10-04 09:05 UTC, hubertp approved these changes
lgtm

2024-10-04 09:05 UTC, hubertp commented on engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
> +        case expressionId if expressionId ne null =>
How is the `null` condition even possible?

2024-10-04 13:15 UTC, JaroslavTulach commented on engine/polyglot-api/src/main/java/org/enso/polyglot/debugger/IdExecutionService.java
> +    public abstract RootNode getRootNode();
There is `(info.getRootNode());` what this method is needed for?

2024-10-04 15:30 UTC, JaroslavTulach requested changes
Please remove the [getRootNode](https://github.com/enso-org/enso/pull/11173#discussion_r1787703602) and provide some explanation of the new methods.

2024-10-04 15:40 UTC, JaroslavTulach commented on engine/polyglot-api/src/main/java/org/enso/polyglot/debugger/IdExecutionService.java
> +    void setExecutionEnvironment(Info info);
I see following code:
```
        Object result = callbacks.findCachedResult(info);

        if (result != null) {
          throw context.createUnwind(result);
        }
        callbacks.setExecutionEnvironment(info);
```
There is little need for this new callback method. Just do whatever is needed in `findCachedResult`.

2024-10-04 15:46 UTC, JaroslavTulach commented on engine/polyglot-api/src/main/java/org/enso/polyglot/debugger/IdExecutionService.java
> +    void resetExecutionEnvironment(Info info);
Two options:
- merge with `updateCachedResult`
- change return type to `newExecutionEnvironmentOrNull`

Or rather just remove these methods and keep only the single `findExecutionEnvironment(Info)`.

2024-10-04 15:48 UTC, JaroslavTulach commented on engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionCallbacks.java
> +      originalExecutionEnvironment = context.getExecutionEnvironment();
What would happen when a node like this is executed multiple times? At least `assert originalExecutionEnvironment == null`

But overall we don't want the state management here. We want to move it to the actual `IdExecutionEventNode`

2024-10-07 16:34 UTC, 4e6 commented on engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
> +        case expressionId if expressionId ne null =>
I remember I added this guard to fix NPE. But I don't remember exactly how the null value appears

2024-10-08 05:04 UTC, JaroslavTulach requested changes
The `IdExecutionService` interface with single method addition looks fine. Few more comments on the engine&instrument side.

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/id/execution/IdExecutionInstrument.java
> +          resetExecutionEnvironment(info);
There is no need to use `info`.

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/id/execution/IdExecutionInstrument.java
> +          EnsoContext.get(info.getRootNode()).setExecutionEnvironment(originalExecutionEnvironment);
`var ctx = EnsoContext.get(this)`;

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/id/execution/IdExecutionInstrument.java
> +      public EnsoRootNode getRootNode() {
The `EnsoRootNode` shall not be propagated outside of the `IdExecutionInstrument`. The method shall be removed from the interface this class implements.

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
> +      Thread.sleep(200)
Ech. `Thread.sleep` doesn't belong into programs and it is better to avoid them in tests too. Please replace with proper `wait/notify` primitives:
```scala
context.waitForOut(200);
```
that will be notified immediately as soon as some output is delivered.

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/ExecutionConfig.java
> +    Map<UUID, ExecutionEnvironment> expressionConfigsBuilder = new HashMap<>();
Out of curiosity: Why the method itself is not typed properly?

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/polyglot-api/src/main/java/org/enso/polyglot/debugger/IdExecutionService.java
> +    Object getExecutionEnvironment(Info info);
Nice. Having just this single method addition in this interface makes me happy. Assuming `getRootNode` will be removed.

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/polyglot-api/src/main/java/org/enso/polyglot/debugger/IdExecutionService.java
> +    Object getExecutionEnvironment(Info info);
I'd rename the method to `findExecutionEnvironment` and document it usually returns `null`.

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/polyglot-api/src/main/java/org/enso/polyglot/debugger/IdExecutionService.java
> +    Object getExecutionEnvironment(Info info);
Why the return value isn't `ExecutionEnvironment` but `Object`?

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
> +                .getThreadExecutionEnvironment()
Can we keep the original `getExecutionEnvironment()` name? If it clashes with the default/global accessor then rename that one to `getDefaultExcecutionEnvironment()`? Or `getGlobalExecutionEnvironment()`?

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
> +  private ExecutionEnvironment contextExecutionEnvironment;
This is the `default` or `global` execution environment, right?

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
> -    return executionEnvironment;
Rename to _global_ or _default_ environment.

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
> +  private final ContextThreadLocal<ExecutionEnvironmentReference> threadExecutionEnvironment =
Why is this variable in the `EnsoLanguage` and not in `EnsoContext`?

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
> +          (ctx, thread) -> new ExecutionEnvironmentReference(ctx.getExecutionEnvironment()));
Wouldn't it be better to initialize the `ContextThreadLocal` with `null`? E.g. 
```java
      locals.createContextThreadLocal(
          (ctx, thread) -> new ExecutionEnvironmentReference(null));
```
I really don't understand how you can differentiate between global state and thread local state? Especially when the _global_ environment is changed?

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
> +  private static final class ExecutionEnvironmentReference {
Replace with `AtomicReference<ExecutionEnvironment>` or just `new ExecutionEnvironment[1]`. I find creation of a completely new class a little bit verbose.

2024-10-08 05:04 UTC, JaroslavTulach commented on engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
> +    return threadExecutionEnvironment.get().getExecutionEnvironment();
The method should be renamed to `getExecutionEnvironment`. In my opinion it should:
```java
var env = threadExecutionEnvironment.get().getExecutionEnvironment();
return env != null ? env : getGlobalExecutionEnvironment();
```

2024-10-08 14:11 UTC, 4e6 commented on engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
> +      Thread.sleep(200)
The output is updated from the Enso program. How do you notify the waiting method in the test?

2024-10-08 14:14 UTC, 4e6 commented on engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/ExecutionConfig.java
> +    Map<UUID, ExecutionEnvironment> expressionConfigsBuilder = new HashMap<>();
Java compiler was not able to resolve the type in the function declaration. It seems fine now.

2024-10-08 14:16 UTC, 4e6 commented on engine/polyglot-api/src/main/java/org/enso/polyglot/debugger/IdExecutionService.java
> +    Object getExecutionEnvironment(Info info);
the `ExecutionEnvironment` id defined in the `runtime` module

2024-10-08 14:19 UTC, 4e6 commented on engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
> +  private final ContextThreadLocal<ExecutionEnvironmentReference> threadExecutionEnvironment =
> Context thread local references must be created during the invocation in the [TruffleLanguage](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/TruffleLanguage.html) constructor.

https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/TruffleLanguage.ContextLocalProvider.html#createContextThreadLocal(com.oracle.truffle.api.TruffleLanguage.ContextThreadLocalFactory)

2024-10-08 16:12 UTC, 4e6 commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
> +  private ExecutionEnvironment contextExecutionEnvironment;
This is the global one. Renamed

2024-10-08 16:20 UTC, 4e6 commented on engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/ExecutionConfig.java
> +    Map<UUID, ExecutionEnvironment> expressionConfigsBuilder = new HashMap<>();
Nope, still results in a compiler error.

2024-10-09 07:57 UTC, JaroslavTulach commented on engine/polyglot-api/src/main/java/org/enso/polyglot/debugger/IdExecutionService.java
> +    Object getExecutionEnvironment(Info info);
OK.

2024-10-09 07:58 UTC, JaroslavTulach approved these changes

2024-10-09 11:04 UTC, jdunkerley approved these changes

2024-10-09 12:09 UTC, merged