Multipart upload for large files
enso-org/enso pull request #11319
Opened 2024-10-14 14:40 UTC by somebody1234

### Pull Request Description
- Close https://github.com/enso-org/cloud-v2/issues/1492
  - Use multiplart upload for large files (>6MB)
    - Split file into chunks of *exactly* 10MB (backend currently returns a fixed number of chunks)
    - Call "start upload", then upload each chunk to S3 (currently sequentially), then "end upload"
  - Files <=6MB (lambda limit) still use the current endpoint

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

2024-10-14 14:41 UTC, somebody1234 commented
@MrFlashAccount @PabloBuchu @indiv0 thoughts? should we perhaps be uploading multiple chunks in parallel? (does that help at all with upload speed?)

2024-10-14 19:39 UTC, PabloBuchu commented
| Files <=6MB (lambda limit) still use the current endpoint
that is not good :( I wanted to remove the old endpoint

2024-10-14 19:40 UTC, somebody1234 commented
ah that should be an easy fix

2024-10-14 19:43 UTC, PabloBuchu commented
also I moved to download from S3 download files (both normal `file` and `project` files) so we should test that. Since download project files uses `get_details` endpoint I guess we need to hide `get_file` behind the flag. Generating presigned url for downloading requires copying project archive to tmp bucket. Its not a big deal if the archive is small but is user generates some big output then we might need to optmize this.

2024-10-15 10:03 UTC, MrFlashAccount requested changes

2024-10-15 10:03 UTC, MrFlashAccount commented on app/gui/src/dashboard/hooks/backendHooks.ts
> +  return useEventCallback(async (params: backendModule.UploadFileRequestParams, file: Blob) => {
We might want to add more API, like cancel or pause if user is offline. Also we want to prevent navigation and warn user that the upload will be cancelled if user close the tab/window

2024-10-15 10:03 UTC, MrFlashAccount commented on app/gui/src/dashboard/hooks/backendHooks.ts
> +    if (backend.type === backendModule.BackendType.local) {
Let's think about how we can unify the API to get rid of the `if` statement here.

2024-10-15 10:03 UTC, MrFlashAccount commented on app/gui/src/dashboard/hooks/backendHooks.ts
> +      const toastId = toast.loading(getText('uploadLargeFileStatus', 0, fileSizeMB))
Lets expose the API to handle upload status outside (isUploading, uploadPercent etc)

2024-10-15 10:03 UTC, MrFlashAccount commented on app/gui/src/dashboard/hooks/backendHooks.ts
> +          toast.update(toastId, {
Lets also decouple toast (presentation) from the uploading itself

2024-10-15 10:03 UTC, MrFlashAccount commented on app/gui/src/dashboard/hooks/backendHooks.ts
> +      } catch (error) {
We want to be able to retry uploading the chunk that failed

2024-10-15 10:03 UTC, MrFlashAccount commented on app/gui/src/dashboard/layouts/AssetsTable.tsx
> +  const uploadFileMutation = useUploadFileMutation(backend)
if it's a `mutation`, then I think it should, at least, expose `isMutating`, `isError`, `error` fields

2024-10-15 10:03 UTC, MrFlashAccount commented on app/gui/src/dashboard/layouts/GlobalContextMenu.tsx
> +          const input = document.createElement('input')
let's move it to an utility function

2024-10-15 10:03 UTC, MrFlashAccount commented on app/gui/src/dashboard/hooks/backendHooks.ts
> +      const toastId = toast.loading(getText('uploadLargeFileStatus', 0, fileSizeMB))
Also: let's move this toast to the bottom-right corner

2024-10-15 10:25 UTC, PabloBuchu commented
1. When I upload a file it appears for a second then its gone and then its back but with a delay after `Finished uploading file`. It is confusing for the users
2. Download a file doesn't work and it is something with FE I guess. Right now when you ask for file/project details we will copy the files to tmp bucket and generate a presigned url to download. When I try to download I am saving `xml` file with <fileid>.. when I manually copy and use s3 url it works. Same with projects
2.1 Should we hide generate presigned behind the flag? Looks like we are copying files to tmp bucket every time for projects
3. Upload enso-archive for already exisitng project. I can click `Update` multiple time and multiple requests are being send. So far managed to click 3. Looks like the same is with rename but harder

2024-10-15 10:30 UTC, somebody1234 commented
> Should we hide generate presigned behind the flag

probably yes

2024-10-21 08:05 UTC, MrFlashAccount approved these changes

2024-10-21 10:38 UTC, farmaazon approved these changes

2024-10-21 14:25 UTC, PabloBuchu approved these changes

2024-10-21 15:31 UTC, merged