Add traces to integration tests + suppress one flaky assertion.
enso-org/enso pull request #11595
Opened 2024-11-19 16:11 UTC by farmaazon

### Pull Request Description

Fixes #11604 

Most issues were caused by a problem with Project List flooding the network with its requests - this was fixed on develop.
But one assertion was flaky - it assumed we will see the "real" run result on `write` node, but sometimes it is immediately overwritten by dry run.

But the most important part of this PR is adding traces to Electron packages - it's should be much easier now to debug E2E test failures.

Also renamed the previously misnamed "E2E tests" to "[GUI] integration tests".

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~
- ~~[ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

2024-11-22 13:52 UTC, somebody1234 commented on app/ide-desktop/client/tests/localWorkflow.spec.ts
> +    // The above check is flaky, because sometimes the additional egine run overrides node output back to "dry run".
`egine` -> `engine`

2024-11-22 13:52 UTC, somebody1234 approved these changes
approving rename of dashboard files only

2024-11-22 13:53 UTC, somebody1234 commented
might wanna update codeowners too due to the change of path

2024-11-22 14:50 UTC, MrFlashAccount commented
@farmaazon why we run `pw` tests in `unit tests` job? 
![CleanShot 2024-11-22 at 17 50 14@2x](https://github.com/user-attachments/assets/419c79ad-3591-43de-aff5-7e0cb8d2141c)

2024-11-22 14:51 UTC, MrFlashAccount requested changes
See the comment above

2024-11-22 20:25 UTC, MrFlashAccount approved these changes

2024-11-27 12:38 UTC, vitvakatu approved these changes

2024-11-27 14:09 UTC, AdRiley approved these changes

2024-11-27 14:09 UTC, merged