Combine context menus into single context menu
enso-org/enso pull request #11763
Opened 2024-12-04 14:49 UTC by somebody1234

### Pull Request Description
- Combine all context menus to a single context menu
- Remove `ContextMenus` component

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~
- [x] ~~If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - ~~If applicable, it is suggested to paste a link to a successful run of the Extra Tests.~~

2024-12-05 10:20 UTC, MrFlashAccount requested changes
Let's add tests if possible

2024-12-10 12:42 UTC, somebody1234 commented
@MrFlashAccount how do the tests look?

2024-12-11 11:22 UTC, MrFlashAccount approved these changes

2024-12-11 11:27 UTC, PabloBuchu commented
Can we disable context menu when clicking `Users` or `Teams`?
<img width="883" alt="Screenshot 2024-12-11 at 12 27 07" src="https://github.com/user-attachments/assets/6682c2dd-09a6-469e-9be9-e78f2356db82">

2024-12-11 12:36 UTC, PabloBuchu approved these changes

2024-12-11 21:32 UTC, merged