Improve sentry support
enso-org/enso pull request #11776
Opened 2024-12-05 06:11 UTC by somebody1234

### Pull Request Description
- Close https://github.com/enso-org/cloud-v2/issues/1590
  - Add source maps to built bundle for sentry to pick up
- Close https://github.com/enso-org/cloud-v2/issues/1589
  - Add global Sentry filter to avoid sending 400 responses from backend

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~
- [x] ~~If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.~~
  - ~~If applicable, it is suggested to paste a link to a successful run of the Extra Tests.~~

2024-12-05 10:13 UTC, MrFlashAccount requested changes
Sentry doesn't pick up the sourcemaps: https://enso-zw.sentry.io/issues/6112647318/?project=4506070404300800&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&statsPeriod=24h&stream_index=0

<img width="946" alt="image" src="https://github.com/user-attachments/assets/7fdcd1fa-ebcc-4dac-afe9-0b1961b60371">

2024-12-16 09:43 UTC, somebody1234 commented
@MrFlashAccount ready for re-CR i think

2024-12-16 09:54 UTC, MrFlashAccount approved these changes

2024-12-16 09:55 UTC, MrFlashAccount commented
@somebody1234 let's merge it and see how it goes

2024-12-16 14:15 UTC, jdunkerley requested changes
The token should not be a variable it should be a secret.

2024-12-16 14:15 UTC, jdunkerley commented on .github/workflows/release.yml
> +          SENTRY_AUTH_TOKEN: ${{ vars.SENTRY_AUTH_TOKEN }}
this should be a secret not a var

2024-12-16 14:15 UTC, jdunkerley commented on app/gui/src/dashboard/index.tsx
> +    // !detect.IS_DEV_MODE &&
deliberately commented out?

2024-12-17 04:09 UTC, somebody1234 commented
@jdunkerley should be ready for re-review

2024-12-17 09:54 UTC, jdunkerley approved these changes
Thanks @somebody1234 - let me know what vars/secrets need added to org.

2024-12-18 13:56 UTC, kazcw approved these changes

2024-12-19 09:26 UTC, merged