Adding my comments to Intersection Types documentation
enso-org/enso pull request #11838
Opened 2024-12-11 16:52 UTC by radeusgd

### Pull Request Description

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

2024-12-11 16:59 UTC, radeusgd commented on docs/types/intersection-types.md
> +> a `Float` value, based on the 'hidden' part of its type.
I want to make it clear that while the syntax is very similar, the checked argument and type-asserting expressions are actually different and behave differently in regard to the 'hidden' types.

2024-12-12 05:37 UTC, JaroslavTulach requested changes
Accepted most of your changes in https://github.com/enso-org/enso/pull/11600/commits/d1cbc8d7d6f04f811a18e51afd0331b3853b2289

2024-12-12 05:37 UTC, JaroslavTulach commented on docs/types/intersection-types.md
> +> module that is only imported in the place that will be constructing the multi-values.
That's correct and exactly as [prototyped in the tests](https://github.com/enso-org/enso/commit/3d8a0e1b90b20cfdfe5da8d2d3950f644a4b45b8#diff-c6ef852899778b52ce6a11ebf9564d102c273021b212a4848b7678e120776287R23).

2024-12-12 05:37 UTC, JaroslavTulach commented on docs/types/intersection-types.md
> +      f : Float -> f.sqrt
Does not work. Reported as
- #11828

2024-12-12 05:37 UTC, JaroslavTulach commented
Accepted as https://github.com/enso-org/enso/pull/11600/commits/d1cbc8d7d6f04f811a18e51afd0331b3853b2289

2024-12-12 05:37 UTC, closed without merging