Add third data quality metric
enso-org/enso pull request #11939
Opened 2024-12-24 11:11 UTC by marthasharkey

### Pull Request Description

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

2025-01-08 15:03 UTC, jdunkerley requested changes
Some tweaks for efficiency but like the approach.

2025-01-08 15:03 UTC, jdunkerley commented on std-bits/table/src/main/java/org/enso/table/data/column/operation/CountWhitespace.java
> +public class CountWhitespace {
Let's create a base class (something like `SampledOperation`), which would hold the `RANDOM_SEED` and `DEFAULT_SAMPLE_SIZE`.

2025-01-08 15:03 UTC, jdunkerley commented on std-bits/table/src/main/java/org/enso/table/data/column/operation/CountWhitespace.java
> +public class CountWhitespace {
`CountWhitespace` feels the wrong name, probably should be `CountNonTrivialWhitespace`.

2025-01-08 15:03 UTC, jdunkerley commented on std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
> +  private Future<Long> whitespaceCount;
Lets create a record type here.

```java
record DataQualityMetrics(Long untrimmedCount, Long whitespaceCount);
```

We can then do it as sinlge CompletableFuture to compute the values.

2025-01-08 15:03 UTC, jdunkerley commented on std-bits/base/src/main/java/org/enso/base/Text_Utils.java
> +            "\u2007", "\r", "\n", "\t", "\u2002", "\u00A0", "\u3000", "\u2003");
`Set<Char>` should work here I think.

The variable name makes me think it is good not bad.

We can then loop over the characters of the `String` and return true if the set contains any of them.

2025-01-08 15:03 UTC, jdunkerley commented on distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
> +        [number_nothing, number_untrimmed, number_non_triv]
Let's change it so we check the count only once. Tiny nit.

2025-01-08 15:55 UTC, radeusgd commented on std-bits/base/src/main/java/org/enso/base/Text_Utils.java
> +            "\u2007", "\r", "\n", "\t", "\u2002", "\u00A0", "\u3000", "\u2003");
I was also confused by the variable name, shouldn't it be `nonTrivialWhiteSpace` instead?

2025-01-08 15:56 UTC, radeusgd commented on std-bits/base/src/main/java/org/enso/base/Text_Utils.java
> +            "\u2007", "\r", "\n", "\t", "\u2002", "\u00A0", "\u3000", "\u2003");
Also, I imagine the JVM is good at optimizing such things, but perhaps we will make it easier for it if we make the list (or Set) a `private static final` field ensuring that it is computed only once upon initialization and not on **every** invocation of this function (since this function may be invoked millions of times).

I imagine the JIT would fold this constant at some point, but making this a constant from the beginning maybe would just be better.

2025-01-08 16:01 UTC, GregoryTravis commented on distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
> +        if (self.value_type == Value_Type.Mixed || self.value_type.is_text).not then Nothing else
```suggestion
        if self.value_type.is_text.not then Nothing else
```

I think Mixed implies is_text.not

2025-01-08 16:01 UTC, GregoryTravis commented on distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
> +        [number_nothing, number_untrimmed, number_non_triv]
```
name_extra = if all_rows_count > Column.default_sample_size then " (sampled)" else ""
```

2025-01-08 16:07 UTC, radeusgd commented on std-bits/base/src/main/java/org/enso/base/Text_Utils.java
> +            "\u2007", "\r", "\n", "\t", "\u2002", "\u00A0", "\u3000", "\u2003");
Other thing - how do we know that this list is comprehensive?

Checking e.g. https://jkorpela.fi/chars/spaces.html suggests that we are missing e.g. the NARROW NO-BREAK SPACE `U+202F` or `U+180E` - the "MONGOLIAN VOWEL SEPARATOR" 😅 

I think that as long as we can reasonably avoid it, I'd rather be against including such lists of constants in our code - it is easy for them to miss some obscure constants, and they are a bit less future proof. If instead we rely on ICU4J or the Java SDK itself, if there are new Unicode versions released in the future we'd just need to rely on them to get updated to the latest version instead of having to update many of such constant lists manually (which we will probably never do unless users start reporting bugs).

Of course things like "MONGOLIAN VOWEL SEPARATOR" are rather obscure and missing them probably won't be a huge deal for a generic metric. But if we can use existing dependencies that we rely on anyway, I'd suggest preferring that.

Thus we could rewrite the code to essentially:
- iterate over every character in the text,
- check if it is _any_ whitespace using `UCharacter::isUWhiteSpace`,
- if it is whitespace - then check if it is 'non-trivial' - a non trivial whitespace is any whitespace that is not the `" "` character.

```java
for (...) {
    char c = str.charAt(i);
    if (UCharacter::isUWhiteSpace(c)) {
        boolean isNonTrivial = c != ' ';
        if (isNonTrivial) { return true; }
    }
    context.safepoint();
}
```

2025-01-08 16:20 UTC, radeusgd commented on std-bits/base/src/main/java/org/enso/base/Text_Utils.java
> +            "\u2007", "\r", "\n", "\t", "\u2002", "\u00A0", "\u3000", "\u2003");
Ah sorry small correction - after further reading perhaps the two examples I provided above may actually not be classified as whitespace by the Unicode standard... So perhaps the List was good.

But I think we can still simplify the code by relying on `isUWhiteSpace`. It will also likely be much faster as it relies on bit-fiddling and boils down to 1 bit check per character instead of 16 independent text searches.

2025-01-08 16:27 UTC, radeusgd commented on distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
> +        if (self.value_type == Value_Type.Mixed || self.value_type.is_text).not then Nothing else
No but this suggestion is not equivalent:

```
(self.value_type == Value_Type.Mixed || self.value_type.is_text).not
===
self.value_type != Value_Type.Mixed && self.value_type.is_text.not
!==
self.value_type.is_text.not
```

The counter-example is a mixed type column - `self.value_type == Value_Type.Mixed`.

Then the first and the equivalent second expression will evaluate to `False` but your suggested (third) expression evaluates to `True`.

2025-01-08 16:29 UTC, radeusgd commented on distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
> +        if (self.value_type == Value_Type.Mixed || self.value_type.is_text).not then Nothing else
I guess it becomes clearer if the condition is named:
```suggestion
        is_eligible_for_whitespace_count = self.value_type == Value_Type.Mixed || self.value_type.is_text
        if is_eligible_for_whitespace_count.not then Nothing else
```

2025-01-08 16:30 UTC, radeusgd commented on distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
> +        [number_nothing, number_untrimmed, number_non_triv]
Yeah it would be much better if we go the `name_extra` route and avoid the duplication in all the `percentage_value` entries.

2025-01-09 14:33 UTC, marthasharkey commented on distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
> +        if (self.value_type == Value_Type.Mixed || self.value_type.is_text).not then Nothing else
I have pulled this out into a function as the same check is done in the other data quality count

2025-01-09 14:44 UTC, marthasharkey commented on std-bits/base/src/main/java/org/enso/base/Text_Utils.java
> -  public static boolean has_leading_trailing_whitespace(String s) {
This was initially written in enso then the logic copied over, now as we are in a java file I have written this how I feel is simpler, happy to revert if the original is preferred

2025-01-09 15:00 UTC, marthasharkey commented on std-bits/base/src/main/java/org/enso/base/Text_Utils.java
> +            "\u2007", "\r", "\n", "\t", "\u2002", "\u00A0", "\u3000", "\u2003");
Yeah I agree not relying on a list seems more reliable and more efficient! I didnt know we already have the isUWhitespace elsewhere so thanks for pointing it out!

2025-01-09 15:38 UTC, radeusgd commented on std-bits/base/src/main/java/org/enso/base/Text_Utils.java
> +    return trimmedString.length() != initialString.length();
The earlier algorithm was working in constant memory. Now it may allocate O(N) (as big as the input string) additional memory (just to throw it away).

I know we shouldn't optimize prematurely but this amount of copying seems slightly concerning if it may be done on huge values.

2025-01-15 17:13 UTC, GregoryTravis commented on distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
> +    is_eligible_for_text_data_metric_count : Value_Type -> Boolean
```suggestion
    can_contain_text : Value_Type -> Boolean
```

Since it's generally useful.

2025-01-15 17:13 UTC, GregoryTravis commented on std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
> +      dataQualityMetricsValues =
The code that constructs `dataQualityMetricsValues` is repeated in this file -- it would be good to separate it out into a helper.

2025-01-15 17:19 UTC, GregoryTravis approved these changes
Looks good, just one suggestion about factoring out some common code.

2025-01-16 13:48 UTC, jdunkerley approved these changes
Agree with @GregoryTravis comment would be worth extracting method to make the DataQualityMetrics. Could be a static in the record type taking the StringStorage.

2025-01-16 13:48 UTC, jdunkerley commented on distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
> +    is_eligible_for_text_data_metric_count value_type =
```suggestion
    private is_eligible_for_text_data_metric_count value_type:Value_Type -> Boolean = 
```

2025-01-16 13:48 UTC, jdunkerley commented on std-bits/table/src/main/java/org/enso/table/data/column/operation/CountNonTrivialWhitespace.java
> +  public static long compute(ColumnStorage storage, long sampleSize, Context context) {
Lets get this merged but we can put the loop code here into SampleOperation and call with a delegate to perform the operation.

2025-01-17 11:05 UTC, radeusgd commented on distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
> +        if (self.value_type == Value_Type.Mixed || self.value_type.is_text).not then Nothing else
> I have pulled this out into a function as the same check is done in the other data quality count

Sounds great

2025-01-30 09:54 UTC, merged