Update codeowners file
enso-org/enso pull request #3161
Opened 2021-11-18 09:03 UTC by farmaazon

### Pull Request Description

Update of the CODEOWNERS file after directory structure refactoring. I added myself as owner on the part I'm interested in.

### Important Notes

### Checklist

Please include the following checklist in your PR:

- ~~[ ] The documentation has been updated if necessary.~~
- ~~[ ] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.~~
- ~~[ ] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/develop/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/develop/docs/style-guide/yaml.md) style guides.~~
- ~~[ ] All code has been tested where possible.~ - How can I test it?

2021-11-18 10:36 UTC, MichaelMauderer approved these changes

2021-11-18 11:14 UTC, 4e6 approved these changes

2021-11-18 13:31 UTC, wdanilo approved these changes

2021-11-18 14:24 UTC, mwu-tow requested changes
You can add me as an owner for the shared rust lirbaries part, as they also power the controllers I'm owning.

2021-11-19 13:25 UTC, mwu-tow approved these changes

2021-11-19 17:10 UTC, merged