Generate type definition for complex atoms
enso-org/enso pull request #3207
Opened 2021-12-24 11:10 UTC by 4e6

### Pull Request Description

PR adds generation of atoms for complex atom definitions, i.e.

```py
type Maybe
    type Some a
    type Nothing
```

The atom Maybe is also generated, so it can be used in conversions, i.e

```py
x.to Maybe
```
or
```py
y.to Json
```

### Important Notes

Stdlib changes:
- Rename method `Meta.meta` to `Meta.repr` to avoid clashing with the `type Meta` atom definition.
- Rename atom `type Os` to `type Platform` to avoid clashing with the `Platform.os` method definition.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/develop/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/develop/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

2021-12-27 07:34 UTC, wdanilo requested changes
This PR pollutes the namespace a lot. See this for example:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/1623053/147446970-a8d5220c-7390-41ba-b884-c1395b882f0b.png">

The Atoms should be accessible in a nested fashion. Sometimes it is desirable to access them without qualified name – then we can import them or re-export them. But by default, the definition 

```
type Maybe
    type Some a
    type Nothing
```

Should create atoms `Maybe.Some` and `Maybe.Nothing`. This is especially important in case we will support in the future the parametrised atoms, think of this definition:

```
type Maybe a
    type Some a
    type Nothing
```

Then, you should be able to access the atoms as `Maybe.Some`, but also as `Maybe Number . Some`. In the later case, the `Some`'s parameter will be constrained.

2021-12-27 08:58 UTC, 4e6 commented
@wdanilo just to clarify, what's happening here:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/1623053/147446970-a8d5220c-7390-41ba-b884-c1395b882f0b.png">

Previously, the code
```py
type Json
    type Array
    type Boolean
...
```

produced atoms `Array`, `Boolean`, etc. in the module `Standard.Base.Data.Json`. This PR only adds the generation of an extra atom `Json` in the module `Standard.Base.Data.Json`.

What's changed:
- In the module `Standard.Base.Data.Json` the new atom `Json` shadows the module name `Json`, and you cannot access atoms using the module name, like `Json.Array` (that's why I had to remove the prefix in the diff)
- In a different module, if you `import Standard.Base.Data.Json`, you can still access atoms using the module name, like `Json.Array` or `Json.Json`

Now, if we want to nest atoms further under the name of their base type, when we `import Standard.Base.Data.Json`, we would have to use `Json.Json.Array` to access the Array atom under the type Json in the module Json.
Or we need to change the importing rules, so that `import Foo` imports both, the module `Foo` and everything from the module `Foo` (how the `from Foo import all` works now)

2021-12-27 11:04 UTC, 4e6 commented
Update (regarding the diff)

In the module `Standard.Base.Data.Json` you can use `here.Array` to refer to the Array atom, but currently this syntax is not supported in the pattern-matching.

2022-01-12 12:57 UTC, 4e6 commented
Discussed this new _nesting_ approach on Discord. I'll try to make it work.

2022-01-12 15:19 UTC, kustosz commented
Hey, just popping in to say that this functionality of actually supporting sum types has been assigned to @ekmett and me, and we'll start working on it soon. Also, the approach taken here seems wrong, as a sum type is not well-represented as an atom (because it is a collection of atoms). This requires some deeper handling in the interpreter.

2022-01-13 11:26 UTC, 4e6 commented
@kustosz thanks for the update. Closing this PR for now.

2022-01-13 11:26 UTC, closed without merging