Data analysts should be able to transform a Table using the remove_columns and reorder_columns functions
enso-org/enso pull request #3240
Opened 2022-01-31 16:23 UTC by radeusgd

### Pull Request Description

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/develop/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/develop/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

2022-02-01 13:04 UTC, jdunkerley requested changes
Needs the changelog updated but otherwise looks good

2022-02-01 13:23 UTC, jdunkerley approved these changes

2022-02-02 08:24 UTC, wdanilo approved these changes
Beautiful!

2022-02-03 14:18 UTC, 4e6 approved these changes

2022-02-03 14:18 UTC, merged