Update CODEOWNERS
enso-org/enso pull request #3247
Opened 2022-02-01 19:21 UTC by jdunkerley

Adding myself to GUI codeowners so can approve `CHANGELOG.md` changes by library team.

Happy to be removed once CHANGELOG in a new common location.

### Pull Request Description

No real changes just expanded code owners list for the `app/gui`.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/develop/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/develop/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

2022-02-02 02:22 UTC, mwu-tow commented
Perhaps this won't be needed, as I'll be moving CHANGELOG.md to the repository root in the immediate future.

2022-02-02 08:07 UTC, wdanilo requested changes
@mwu-tow when it will happen?
@jdunkerley I think you should add yourself only to the CHANGELOG.md changes, not the whole GUI folder.

2022-02-02 08:08 UTC, mwu-tow commented
> @mwu-tow when it will happen? @jdunkerley I think you should add yourself only to the CHANGELOG.md changes, not the whole GUI folder.

@wdanilo 
It is a part of https://github.com/enso-org/enso/pull/3241

2022-02-02 08:13 UTC, farmaazon commented on .github/CODEOWNERS
> +/app/gui/ @MichaelMauderer @wdanilo @farmaazon @mwu-tow @jdunkerley
As I'm a bit tired of being spammed with PRs which does not affect my area of knowledge, I'd consider removing the ownership from the CHANGELOG; usually someone competent should review PRs anyway.
```suggestion
/app/gui/ @MichaelMauderer @wdanilo @farmaazon @mwu-tow
/app/gui/CHANGELOG.md
```

2022-02-03 14:16 UTC, radeusgd commented
I think we should also add me and James to `/test/` because this is the location where we keep tests for our libraries. Currently only @4e6 is the owner of that - but it seems there is no need to bother the engine team with every library changing PR (and obviously almost every PR will need to change tests).

2022-02-04 15:45 UTC, ekmett commented
Meanwhile, can someone who _is_ approved finally go fix https://github.com/enso-org/enso/pull/3227 since it dares to touch that file so i can move on with my life?

2022-02-07 06:58 UTC, wdanilo approved these changes

2022-02-08 09:23 UTC, PabloBuchu approved these changes

2022-02-08 09:26 UTC, merged