Add code allowing calculation of EnsoGL stats summaries
enso-org/enso pull request #3252
Opened 2022-02-04 13:58 UTC by akavel

### Pull Request Description

WIP

https://www.pivotaltracker.com/story/show/181093920

### Important Notes

[ci no changelog needed]

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- [ ] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/develop/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/develop/docs/style-guide/yaml.md) style guides.
- [ ] All code has been tested where possible.

2022-02-07 11:41 UTC, wdanilo requested changes
The code is 100% correct, however, nothing is using this code. I have always a big trouble when merging dead code, so I'd prefer not to merge it until this PR introduces anything that actually uses this code.

2022-02-07 11:41 UTC, wdanilo commented on lib/rust/ensogl/core/src/debug/stats.rs
> +        => min: $min:literal avg: $avg:literal max: $max:literal)*) => {
Please format this code. In such complex cases, just make it multiline.

2022-02-07 11:41 UTC, wdanilo commented on lib/rust/ensogl/core/src/debug/stats.rs
> +        );
that's a really nice way of doing tests!

2022-02-07 17:07 UTC, akavel commented
@wdanilo I added a demo scene: it showcases the feature and provides an example of how the summarization API is intended to be used. As mentioned by @MichaelMauderer in chat, those utilities are planned to be further used soon in https://www.pivotaltracker.com/story/show/181151201, which is waiting for them to be completed. Would the above unblock this PR for potential merging?

2022-02-08 09:18 UTC, wdanilo approved these changes
The new demo scene is amazing!

2022-02-08 09:21 UTC, akavel commented
(*Process note:* the code-review is now accepted, therefore the PR is waiting for Review by @MichaelMauderer on Task https://www.pivotaltracker.com/story/show/181093920 before merge.)

<blockquote><div><strong><a href="https://www.pivotaltracker.com/story/show/181093920">Add code allowing calculation of EnsoGL stats summaries - Pivotal Tracker</a></strong></div></blockquote>

2022-02-08 13:57 UTC, MichaelMauderer approved these changes

2022-02-08 13:58 UTC, merged