In main loop, add `on_stats_available` callback
enso-org/enso pull request #3254
Opened 2022-02-07 10:53 UTC by akavel

### Pull Request Description

WIP

https://www.pivotaltracker.com/story/show/181093832

### Important Notes

[ci no changelog needed]

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- [ ] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/develop/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/develop/docs/style-guide/yaml.md) style guides.
- [ ] All code has been tested where possible.

2022-02-08 16:54 UTC, wdanilo requested changes

2022-02-08 16:54 UTC, wdanilo commented on lib/rust/ensogl/core/src/display/world/stats.rs
> +    pub fn begin(&mut self) -> Option<StatsData> {
Why function that "Returns a snapshot of statistics data for the previous rendering frame ..." is called "begin"? For me that does not make sense now and I do not understand the behavior/semantics of this function anymore.

2022-02-08 16:54 UTC, wdanilo commented on lib/rust/ensogl/core/src/display/world/stats.rs
> +    are_stats_valid : bool,
I'm missing info why this is tracked and what does this information influence. I was trying to read that from the other changes, but then I have seen that function "begin" does something strange and I'm lost right now in understanding of the logic here.

2022-02-09 12:01 UTC, akavel commented
@wdanilo I did some refactoring inspired by your comments; would you possibly find the code clearer now?

2022-02-09 12:34 UTC, wdanilo approved these changes
Yup, it's very clear now!

2022-02-09 13:19 UTC, akavel commented
(*Process note:* the code-review is now accepted, therefore the PR is waiting for Review by @MichaelMauderer on Task https://www.pivotaltracker.com/story/show/181093832 before merge.)

2022-02-15 10:49 UTC, merged