Add API for component groups
enso-org/enso pull request #3286
Opened 2022-02-18 08:40 UTC by 4e6

### Pull Request Description

PR ads two new commands to the Language Server protocol
- `library/getPackage` to get the package definition of the provided library
- `editions/listDefinedComponents` to get the list of available components in the provided edition

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH `./run dist` and `./run watch`.

2022-02-22 20:25 UTC, radeusgd commented on docs/language-server/protocol-language-server.md
> +}
If the fields can be ommitted, shouldn't they be marked with the `?` ?

2022-02-22 20:25 UTC, radeusgd commented on docs/language-server/protocol-language-server.md
> +  icon?: string;
This is not directly related to this PR but out of curiosity - why can we specify the icon/color here if all we are doing is extending an existing component group? Won't it be ignored as the ones from the base component group would be used? Or am I misunderstanding something?

2022-02-22 20:25 UTC, radeusgd commented on docs/language-server/protocol-language-server.md
> +  moduleName: string;
May be worth clarifying if the `moduleName` contains the `libraryName` as prefix or if it is cut as it is implicit (probably the latter).

2022-02-22 20:25 UTC, radeusgd commented on docs/language-server/protocol-language-server.md
> +interface ComponentGroup {
```suggestion
interface ExtendedComponentGroup {
```

2022-02-22 20:25 UTC, radeusgd commented on docs/language-server/protocol-language-server.md
> +interface ComponentGroup {
```suggestion
interface LibraryComponentGroup {
```
Shouldn't the name here be consistent with the header?

2022-02-22 20:25 UTC, radeusgd commented on docs/language-server/protocol-language-server.md
> +All returned fields are optional, as they may be missing.
If all are missing, probably `license` should also have a question mark.

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/main/scala/org/enso/languageserver/libraries/ComponentGroupsResolver.scala
> +        .toMapKeepFirst(libraryComponents)
Why is the `keep first` needed? Can we ever find two configs for the same library name? Maybe in such a situation we should at least log a warning that another config was ignored?

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/main/scala/org/enso/languageserver/libraries/ComponentGroupsResolver.scala
> +        }
Hm not sure how important that is - probably best to checkout in the IDE and then it doesn't matter, but feels like adding type signatures to these 3 definitions would make it easier to understand what is happening here when reading the diffs.

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/main/scala/org/enso/languageserver/libraries/ComponentGroupsResolver.scala
> +    }
This just feels so weird that a mutable map is being constructed by a fold.
If it's a fold - maybe it should use an immutable structure?
If using a mutable hashmap is faster, why not just use `each` here or use a `for` loop? Folding suggests that the passed through `m` changes its value - but as a reference to a mutable object, it itself remains constant so there's no need to pass it through.

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/main/scala/org/enso/languageserver/libraries/ComponentGroupsResolver.scala
> +    }
Also - do we need to expose that this map is mutable? Maybe when it is returned it could be upcast to `collection.Map` (or `MapView`) which hides the mutability?

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/main/scala/org/enso/languageserver/libraries/ComponentGroupsResolver.scala
> +        .groupByKeepFirst(newLibraryComponentGroups) { libraryComponentGroup =>
Again - is it ever possible that the `ModuleReference` will be duplicated?
We already deduplicated the libraries earlier, so at this stage a library would need to declare duplicated component groups, right? If this is even allowed, shouldn't a warning be reported somewhere?

It feels like silently ignoring entries like these may lead to hard to detect errors somewhere down the line (but maybe in this particular case I'm misunderstanding something?)

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/main/scala/org/enso/languageserver/libraries/ComponentGroupsResolver.scala
> +    }
This just feels weird - why can't we just do a `mapValues` like on an immutable map?

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/main/scala/org/enso/languageserver/libraries/ComponentGroupsResolver.scala
> +      icon    = extendedComponentGroup.icon.orElse(libraryComponentGroup.icon),
Shouldn't the original color/icon take precedence over the ones defined by the extension? Or is it deliberate that the extension will have the override? (Although that is weird, someone can create a library which will change the color and icon of some base component groups from stdlib? won't that be confusing to the users?)

Also here - the result will depend on the order in which these are resolved - but is the order of `packages: Iterable[Config]` (on which the order of these will rely) at the input specified in any way in `run`? Maybe we should sort the `packages` by name or something - to ensure that the order is static / consistent between runs and platforms (for example if the `packages` is constructed by listing filesystem directories, I think the order in which they would be returned can easily vary between operating systems - potentially leading to component groups looking differently based on the OS).

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/main/scala/org/enso/languageserver/libraries/LibraryApi.scala
> +      raw: JsonObject
I'm wondering if it would be worth to add something like `temporary` to the name of this variable to more directly indicate that it is going to disappear in a while.

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/main/scala/org/enso/languageserver/libraries/LocalLibraryManager.scala
> +      componentGroups = config.componentGroups.toOption,
It will be an option if it failed to parse, right? (If it parsed correctly it will be an empty list instead, right?)

I don't like that we are swallowing errors. I'd suggest at least logging a warning here, specifying the parse error.
But ideally - the error should be forwarded to the IDE as part of the response payload (i.e. for this specific library instead of having a missing field, there could be some other field indicating that this failed to parse; the bulk operation that parses all libraries could include a list of modules which failed to parse, ideally each with the associated error).

I understand that this adds work and is not crucial for an MVP, so maybe it does not need to be done as part of this task - but I would at least suggest to create a task to deal with it at some point. I think it's pretty important to _not_ swallow errors, as this will become a source of confusion for the users at some point: imagine the scenario where a user edits the component group in such a way that it fails to parse - they will stop seeing the respective component groups but will otherwise get no indication of error.

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/EditionsListDefinedComponentsHandler.scala
> +            }
Again, shouldn't libraries for which the config could not be loaded be indicated somehow? Just ignoring them feels a bit bad. If not in this iteration, at least a TODO could be left for the future - otherwise I'd think it will be unlikely this gets revisited.

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/LibraryGetPackageHandler.scala
> +class LibraryGetPackageHandler(
The implementation of this class looks so similar to `LibraryGetMetadataHandler` that I'm wondering if maybe it would be worth to separate out the shared logic to avoid repeating it?

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/test/scala/org/enso/languageserver/libraries/ComponentGroupsResolverSpec.scala
> +    "skip component groups extending nothing" in {
Again, shouldn't this be reported somewhere as a warning?

If I make a typo in specifying what existing group I want to extend, my extensions will just not show up - not very helpful when trying to figure out what was the issue. Not saying this is necessary from the beginning, but at least an indication that it should be added at some point would IMO be good.

2022-02-22 20:25 UTC, radeusgd commented on engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
> +          }
Maybe you could somehow fake the current edition to have any component groups? Feels like the test is a bit incomplete if only the path leading to 'no results' is tested.

2022-02-22 20:25 UTC, radeusgd commented on lib/scala/library-manager/src/main/scala/org/enso/librarymanager/published/CachedLibraryProvider.scala
> +    extends PublishedLibraryCache {
This comment is not valid anymore - this class no longer implements the `PublishedLibraryProvider` interface, like suggested in the doc comment.

2022-02-22 20:34 UTC, radeusgd requested changes
Overall - looks really great; it took me quite a while to review this as this is adds quite a lot of functionality.

1. Some comments on documentation that I think should be addressed before merging (inconsistent names etc.)

Then some lower priority stuff but would be cool if addressed:
2. As written in comments above - in multiple places we swallow errors regarding parsing and handling of component groups. This seems bad to me - the users will be confused why their defined groups do not show up without getting any cues. While I understand this may not be the most pressing feature at this stage - I think it would be good to at least mark these relevant places with a TODO and adding a task to address this - so that we can keep track of the places that will need to be revisited to have proper error handling.
3. Some weird style where a mutable data structure is handling using operations associated with immutable structures (folding where the accumulator is a mutable map) - while not incorrect, it just looks strange (that is a bit subjective though). I'd suggest maybe changing this to be more uniform - either by using immutable structures or by writing more imperative code using mutable structures - the mixup just looks a bit weird.
4. If possible, would be cool to integration test the `editions/listDefinedComponents` endpoint - as (unless I missed something which is not out of question) seems like is only tested with the scenario where no components are returned - which seems a bit lacking.

2022-02-23 10:48 UTC, 4e6 commented on docs/language-server/protocol-language-server.md
> +}
Yes, you're right. I thought that `?` indicates nullable fields in TypeScript, but turned out it also indicates an absence of a field.

2022-02-23 10:52 UTC, 4e6 commented on docs/language-server/protocol-language-server.md
> +  icon?: string;
I thought that is from the design document. But when I checked again, it seems that you should not be able to override the color and icon of an existing group. I'll remove those fields.

2022-02-24 10:05 UTC, 4e6 commented
@radeusgd thanks for the review. I managed to address most of your comments.
1. API is adjusted. I removed redundant fields, fixed the names
2. Implemented config verification and error logging. In the future can extend it and send the verification errors to the client
3. I changed the data structures returned from grouping combinators to immutable ones. Although I believe that folding with the mutable reference is fine, because it does not affect the referential transparency (you will still get the same result as with immutable one)
4. I was not able to mock the edition in order to implement a proper test. The result of this test will be filled with component groups when we add them to the standard library

2022-02-24 10:51 UTC, radeusgd approved these changes
Awesome!

> 2. Implemented config verification and error logging. In the future can extend it and send the verification errors to the client

Looks perfect. I think we should add a way to send the errors to the client, but totally understandable to make this a separate task (and probably not the top-priority). Do you think it's worth creating a task in Pivotal to at least keep it somewhere in the Icebox?

> 3. I changed the data structures returned from grouping combinators to immutable ones. Although I believe that folding with the mutable reference is fine, because it does not affect the referential transparency (you will still get the same result as with immutable one)

I totally agree that folding a mutable reference is fine - in the sense that it is correct. It is just an uncommon pattern which IMO may be confusing when reading it (mixing imperative and functional constructs like this). But that is just a subjective code-style opinion, so I'm not pushing it.

> 4. I was not able to mock the edition in order to implement a proper test for the `listDefinedEditions`. The result of this test will be filled with component groups when we add them to the standard library

Yeah, I expected this may be problematic. Would be good to have it, but if the component groups are going to be added to the standard library relatively soon, I guess we are good (not much value in implementing a mock which will not be necessary soon).
Would be cool to temporarily add a component group to stdlib and at least test it manually/locally - just as a sanity check. Unless you already did that :)

2022-02-24 12:41 UTC, merged