Enso Formatter
enso-org/enso pull request #3329
Opened 2022-03-08 22:52 UTC by wdanilo

### Pull Request Description

This PR implements a custom Enso Formatter for common code patterns that are not covered by Rust fmt. It does not extend Rust fmt because it requires **a lot** more work, while this tool is meant to make our life just a little bit easier. For now it supports the following auto formatting:

- Sorting imports into groups.
- ~Warnings about star imports that are not ending with `traits::*` or `prelude::*`~ (almost).
- Sorting module attributes into groups.
- Adding standard lint configuration to `lib.rs` and `main.rs`.

The whole implementation is pretty simple and can be found in the [`build/enso-formatter/src/main.rs` file](https://github.com/enso-org/enso/blob/wip/wd/enso-formatter2/build/enso-formatter/src/main.rs).

For example, EnsoGL core `lib.rs` is automatically reformatted to:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/1623053/157158945-944ad065-0976-454c-9c56-32f9fe34216d.png">

### Important Notes

This adds tons of warnings to our codebase. These will be sorted (disabled per file or fixed) before merging this PR.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- ~All code has been tested:~
  - ~[ ] Unit tests have been written where possible.~
  - ~[ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH `./run dist` and `./run watch`.~

2022-03-09 00:06 UTC, wdanilo commented
@MichaelMauderer integrating it right now with the `./run` script does not make sense, as it requires some magic with building rust while evaluating the script, and @mwu-tow is slowly getting his `./run` Rust script ready. So I think we should integrate it then. For now, just run it from Intellij and it will just work.

2022-03-09 14:29 UTC, mwu-tow requested changes

2022-03-09 14:29 UTC, mwu-tow commented on app/gui/controller/engine-model/src/lib.rs
> +// === Standard Linter Configuration ===
I don't think this is desired — empty section.

2022-03-09 14:29 UTC, mwu-tow commented on app/gui/controller/engine-protocol/src/common/error.rs
> +
Do we want to introduce 3 empty lines if there are no sections?

2022-03-09 14:29 UTC, mwu-tow commented on app/gui/controller/engine-protocol/src/generated/binary_protocol_generated.rs
>  use std::cmp::Ordering;
It seems that comment was deleted.

2022-03-09 14:29 UTC, mwu-tow commented on app/gui/controller/engine-protocol/src/generated.rs
> -// We don't want warnings for the generated code.
Comment lost.

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +        out.push_str(&format!("// ===={}====\n", "=".repeat(str.len())));
sth like 
```
writeln!(out, "// ===={}====\n", "=".repeat(str.len())); 
```
could work here, I think

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +    if tokens.iter().map(|tok| map.contains_key(tok)).any(|t| t) {
Why not put the check in `any`?

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +    ModuleAttribFeature2 = r"#!\[allow\(incomplete_features\)\]";
I think this should be just `ModuleAttribAllow` case.
If for some reason this needs to be separate, it should be named better.

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +fn find_with<T>(input: &str, regex: &Regex, f: impl FnOnce(String) -> T) -> Result<(), T> {
I dislike using Result to short-circuit returns of "correct" values. Would using just early returns be feasible instead?

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +fn re(input: &str) -> Regex {
Let's think of a better name.

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +    let sub_results: Vec<bool> = t.iter().map(|t| print_single(out, map, *t)).collect();
why do we collect only to iterate again?

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +    Preview,
What is preview? Something like dry run?

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +    let md = fs::metadata(path).unwrap();
Why unwrap rather than return Result and give caller a choice how to handle issue?
(I know that this is a script so panics are not that much issue but still…)

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +        let is_main_file = file_name == Some("lib.rs") || file_name == Some("main.rs");
This should also cover all rust files in the `bin` and `tests` crate subdirectories.

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +        println!("[{}/{}] Processing {:?}{}.", i + 1, total, sub_path, dbg_msg);
Don't use debug formatter for printing paths, use `sub_path.display()`.

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +            .stdout(Stdio::inherit())
Not needed, out is by default inherited.

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +            .spawn()
Use `status()`, rather than spawn + wait.

The returned exit status should be checked (see `exit_ok`)

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +            .args(["fmt"])
use `arg("fmt")`

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +        let mut child = Command::new("cargo")
Are we safe regarding to what current_dir might be?

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +            Some(mut m) => {
`if let` might be clearer here

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +            Some(mut m) => {
or even `while let`

2022-03-09 14:29 UTC, mwu-tow commented on build/enso-formatter/src/main.rs
> +    let incorrect_ending_len = ending.into_iter().skip_while(|t| t.token == EmptyLine).count();
can't this be done as a single chain?

2022-03-09 18:49 UTC, wdanilo commented on build/enso-formatter/src/main.rs
> +        out.push_str(&format!("// ===={}====\n", "=".repeat(str.len())));
From call: writeln returns a Result, so lets leave as is.

2022-03-09 18:56 UTC, wdanilo commented on build/enso-formatter/src/main.rs
> +    let sub_results: Vec<bool> = t.iter().map(|t| print_single(out, map, *t)).collect();
Note from call : add comment or use fold instead.

2022-03-09 19:00 UTC, wdanilo commented on build/enso-formatter/src/main.rs
> +    let md = fs::metadata(path).unwrap();
note from call: Let's leave it this way and use @mwu-tow's library when it will be available.

2022-03-09 19:09 UTC, wdanilo commented on build/enso-formatter/src/main.rs
> +    let incorrect_ending_len = ending.into_iter().skip_while(|t| t.token == EmptyLine).count();
check itertools

2022-03-09 19:09 UTC, wdanilo commented on build/enso-formatter/src/main.rs
> +    let incorrect_ending_len = ending.into_iter().skip_while(|t| t.token == EmptyLine).count();
note from call: `rev` requires double iterator which is not implemented here

2022-03-09 19:10 UTC, mwu-tow approved these changes

2022-03-10 03:28 UTC, wdanilo commented on app/gui/controller/engine-protocol/src/common/error.rs
> +
There should always be a section, so yes.

2022-03-10 04:34 UTC, wdanilo commented on app/gui/controller/engine-protocol/src/generated.rs
> -// We don't want warnings for the generated code.
Comments below the module docs are preserved now.

2022-03-10 04:36 UTC, wdanilo commented on build/enso-formatter/src/main.rs
> +fn find_with<T>(input: &str, regex: &Regex, f: impl FnOnce(String) -> T) -> Result<(), T> {
Since this was macro-ed, yes

2022-03-10 05:03 UTC, wdanilo commented on build/enso-formatter/src/main.rs
> +            Some(mut m) => {
After trying both versions, I'd stay with match - its much more clear to me.

2022-03-10 05:25 UTC, wdanilo commented
After applying the comments, this was pushed to develop by accident.

2022-03-10 05:25 UTC, closed without merging