Drop down for Text.trim 'where' attribute
enso-org/enso pull request #3407
Opened 2022-04-19 14:44 UTC by JaroslavTulach

### Pull Request Description

Based on [Dmitry's hints](https://docs.google.com/document/d/16B5DT7fkToJdUZVHNE6YhKy_TFYAEsRXym-mRPH2L_c/edit#heading=h.k35tiw5lnnk3):
- _Extend the [Suggestion](https://github.com/enso-org/enso/blob/e8dfc6d270ef084a1b5d9c6bd3bbadd8aff1d919/engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala) record so that it can hold information_
- _In the [SuggestionsBuilder](https://github.com/enso-org/enso/blob/e8dfc6d270ef084a1b5d9c6bd3bbadd8aff1d919/engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala) populate suggestion records with new extended type data_

This PR expands the `Suggestion.Attribute` structure with optional `tagValues` hints. It hard-codes these data for the `Text.trim` method. If we managed to transfer these data to the IDE, display it and use it, we'd have a solid 1st prototype of trivial static drop downs.

### TODO

[Dmitry also noted](https://docs.google.com/document/d/16B5DT7fkToJdUZVHNE6YhKy_TFYAEsRXym-mRPH2L_c/edit#heading=h.k35tiw5lnnk3):
- Update JSON codecs of suggestion records in the [org.enso.languageserver.search.SearchProtocol](https://github.com/enso-org/enso/blob/e8dfc6d270ef084a1b5d9c6bd3bbadd8aff1d919/engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala)

That might be necessary step before IDE can accept the newly transmitted `tagValues` and use them.

### Important Notes

It is not the goal of this PR to extract the information directly from the standard library. Enhancing the Enso language type system to provide enough information and extracting them for the `Text.trim` method is a task for another, orthogonal PR.

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH `./run dist` and `./run watch`.

2022-04-19 15:37 UTC, hubertp reviewed
lgtm so far

2022-04-21 10:14 UTC, kustosz requested changes
This is nice in its simplicity, but way too brittle I'm afraid. The IDE needs slightly more understanding – like what `Location` is and where it comes from. What I'm saying is, pasting the string `Location.Both` is rather incorrect, if `Location` is not an imported symbol. Or if someone did:
```
import Standard.Base.Text.Location as Text_Location
```
The IDE _must_ understand how to handle such renames or auto-imports.

2022-04-22 09:44 UTC, JaroslavTulach commented
> This is nice in its simplicity, 

Intentionally oversimplified.

> but way too brittle I'm afraid. The IDE needs slightly more understanding – like what `Location` is and where it comes from...
> `Location.Both` is rather incorrect, if `Location` is not an imported symbol. 

Imports! NetBeans IDE has a special [TreeMaker support](https://github.com/apache/netbeans/blob/2760a68bdae773d322082ba84b216d6c6d7c598c/java/java.source.base/src/org/netbeans/api/java/source/TreeMaker.java#L1006) to create _a qualified identifier; Simple name will automatically be used if appropriate, adding any needed imports, following user's preferences_. To follow the same approach we could say that `tagValues` are supposed to contain fully qualified names. Then it'd be up to the IDE to handle its imports.

The other approach is to delegate the responsibility to the engine runtime & its language server. The engine would then be responsible for updating the source:
- either by specifying in advance what to do when the selection is made
- or be notified that the selection was made and "realize it"

Specifying this  _in advance_ as part of every `Suggestion.Attribute` may be too costly. Moreover such suggestion would be context sensitive - different depending on the source that calls the function. Are we left with FQNs or a callback on selection?

2022-04-22 10:23 UTC, kustosz commented
> To follow the same approach we could say that tagValues are supposed to contain fully qualified names.

I think this is the most sensible approach for now. And the IDE already deals with qualified names in other places, I think. And they have systems for deciding "is this symbol imported already?" and other such queries. Summoning @4e6 to make sure.

2022-04-25 14:12 UTC, JaroslavTulach commented
> ... sensible approach for now ... the IDE already deals with qualified names ...

OK, let's treat the names as qualified.

2022-04-29 04:29 UTC, JaroslavTulach commented
This PR is no longer relevant after Marcin implemented his #3422 - closing.

2022-04-29 04:29 UTC, JaroslavTulach commented
This PR is no longer relevant after Marcin implemented his #3422 - closing.

2022-04-29 04:29 UTC, closed without merging