Implement multi-process message visualisation.
enso-org/enso pull request #3423
Opened 2022-04-28 15:32 UTC by MichaelMauderer

### Pull Request Description

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH `./run dist` and `./run watch`.

2022-04-29 09:56 UTC, wdanilo requested changes

2022-04-29 09:56 UTC, wdanilo commented on lib/rust/ensogl/component/sequence-diagram/src/labeled_line.rs
> +    fn default() -> Self {
A lot of missing docs here - please be sure that linter is enabled. Is Clippy telling about it? If not, why?

2022-04-30 04:02 UTC, kazcw approved these changes

2022-04-30 04:02 UTC, kazcw commented on lib/rust/ensogl/core/src/gui/style.rs
> +    use $crate::prelude::*;
`use` inside a macro imports into the callee's namespace and may cause surprises.

2022-04-30 04:02 UTC, kazcw commented on lib/rust/ensogl/component/sequence-diagram/src/lib.rs
> +        if let [profile_a, profile_b] = profiles {
Should have some handling for the `else` case (at least clear any previous diagram).

2022-04-30 04:02 UTC, kazcw commented on lib/rust/ensogl/component/sequence-diagram/src/lib.rs
> +/// /// Internal model of the SequenceDiagram.
///

2022-05-03 06:11 UTC, wdanilo approved these changes

2022-05-03 09:40 UTC, merged