Adjust Table.sort_columns to use Text_Ordering design
enso-org/enso pull request #3487
Opened 2022-05-26 12:28 UTC by radeusgd

### Pull Request Description

Implements https://www.pivotaltracker.com/story/show/182195306

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run.sh ide dist` and `./run.sh ide watch`.

2022-05-26 17:14 UTC, jdunkerley requested changes
Slight change but really like the clean up

2022-05-26 17:14 UTC, jdunkerley commented on distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
> +         'ś' . starts_with 's' (Regex_Matcher) == True
presumably can do `Regex_Matcher` now without the brackets

2022-05-30 08:37 UTC, jdunkerley approved these changes

2022-05-30 09:47 UTC, hubertp approved these changes

2022-05-30 12:26 UTC, merged