Implement reversion of nodes after editing via searcher.
enso-org/enso pull request #3613
Opened 2022-07-26 07:44 UTC by MichaelMauderer

### Pull Request Description
Add functionality to revert a node that was changed during editing through the searcher. 
Note that currently, nodes are not edited by the searcher, except upon confirmation, Thus this functionality results in a no-op at the moment.

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide dist` and `./run ide watch`.

2022-07-27 13:14 UTC, farmaazon reviewed
Actually, as I've checked the aborting editing... do not revert the expression at the moment. I think this is a regression. So we actually _can_ check if this branch fixes it.

2022-08-01 08:41 UTC, MichaelMauderer commented
> Actually, as I've checked the aborting editing... do not revert the expression at the moment. I think this is a regression. So we actually _can_ check if this branch fixes it.

After checking, it appears that this is not fixed by this PR at the moment. Only the source code is reverted, the view logic was not changed and seems not to revert right away, only after some other update triggers a re-evaluation of the view expression.

2022-08-05 12:34 UTC, farmaazon approved these changes

2022-08-08 08:16 UTC, MichaelMauderer commented
> > Actually, as I've checked the aborting editing... do not revert the expression at the moment. I think this is a regression. So we actually _can_ check if this branch fixes it.
> 
> After checking, it appears that this is not fixed by this PR at the moment. Only the source code is reverted, the view logic was not changed and seems not to revert right away, only after some other update triggers a re-evaluation of the view expression.

The tracking issue is filed here: https://www.pivotaltracker.com/story/show/182926584
This should be fixed in a later stage of the user story that reworks some of the related functionality.

2022-08-09 11:19 UTC, wdanilo requested changes

2022-08-09 11:19 UTC, wdanilo commented on app/gui/src/controller/searcher.rs
> +                tracing::warn!("Tried to revert edited node, but found not edit metadata.");
Please check the sentences with gramarly or something similar. This should be "... , but no edit metadata was found.". Also, what does it mean "revert edited node". You are not reverting the node, rather reverting its expression to the previous state, right? For example, node icons are not reverted? I believe that naming / explanations should be improved here and possibly in other places too.

2022-08-09 11:19 UTC, wdanilo commented on app/gui/src/controller/searcher.rs
> +                    "Reverting node {} after edit reverted. Expression to revert: {}",
What does mean "Reverting node {} after edit reverted"? I do not understand this sentence TBH. Also, is the "Expression to revert" the old one or the new one?

2022-08-09 11:19 UTC, wdanilo commented on app/gui/src/controller/searcher.rs
> +            Box::new(|m| {
`m` is really bad variable name. Does it refer to "module"? (this is my first guess).
Edit: Ahh, it is "metadata" – IMO if the reference to the expanded name is not in the same line or in the previous line, the lambda should use more expresive names.

2022-08-09 11:19 UTC, wdanilo commented on app/gui/src/controller/searcher.rs
> +            tracing::debug!("Not reverting node expression after edit.")
Here the sentence is correct! It tells about reverting EXPRESSION, not the node.

2022-08-09 11:19 UTC, wdanilo commented on app/gui/src/controller/searcher.rs
> +        // Edit node
This is not a sentence.

2022-08-09 11:19 UTC, wdanilo commented on app/gui/src/controller/searcher.rs
> +        // Edit node
not a sentence

2022-08-11 15:14 UTC, wdanilo approved these changes

2022-08-12 07:55 UTC, merged