Parser: implement import
enso-org/enso pull request #3627
Opened 2022-07-29 13:17 UTC by kazcw

### Pull Request Description

Based on usage; I believe this handles every case in current `.enso` files.

### Important Notes

- `import` is a built-in macro, so an import statement parses as a `MultiSegmentApp`.

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide dist` and `./run ide watch`.

2022-07-29 16:50 UTC, JaroslavTulach commented on lib/rust/parser/tests/parse.rs
> +            (MultiSegmentApp #(((Ident import) (OprApp (Ident project) (Ok ".") (Ident IO)))))]),
Why do you believe an `import` shall parse as `MultiSegmentApp`?

2022-07-29 17:44 UTC, JaroslavTulach requested changes
Please created `Tree.Import` and capture the import info in there.

2022-07-29 17:46 UTC, kazcw commented
We are implementing this sort of thing with macros

2022-08-01 05:30 UTC, JaroslavTulach commented
If I properly remember our yesterday conversation, then `MultiSegmentApp` is suitable representation for `if/then/else`, but `import` would benefit from its own `Tree` structure. The less logic I can do in [TreeToIr](https://github.com/enso-org/enso/pull/3611/files#diff-ba87b05069ce6d6bc2bcc063f40bf85389597c107af7f20352604b701eb7ad86) the better.

2022-08-02 12:57 UTC, JaroslavTulach commented on lib/rust/parser/tests/parse.rs
> +    let expected = block![
+1, thanks for this test.

2022-08-02 13:01 UTC, JaroslavTulach approved these changes
Looks fine. Chatting with Kaz over the table revealed that `import` is a Java keyword and we need to prefix the field with something. Otherwise OK.

2022-08-02 15:09 UTC, merged

2022-08-09 04:39 UTC, JaroslavTulach commented on lib/rust/metamodel/src/java/from_meta.rs
> +            let mut name_ = meta::FieldName::from_snake_case("field");
This change renamed even the public getters. Now I see `Line.getFieldExpression()` methods & co.