Fix benchmarks
enso-org/enso pull request #3639
Opened 2022-08-09 16:16 UTC by 4e6

[ci no changelog needed]

### Pull Request Description

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] ~If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide dist` and `./run ide watch`.~

2022-08-09 18:08 UTC, kustosz approved these changes
Awesome, just one change I'd do differently, otherwise we have 2 identical benchmarks

2022-08-09 18:08 UTC, kustosz commented on engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/AtomFixtures.scala
> +      |    generator = acc -> i -> if i == 0 then acc else @Tail_Call generator (Cons i acc) (i - 1)
Should be List.Cons – the point of this benchmark is to verify there's no overhead in the qualified form.

2022-08-10 03:49 UTC, JaroslavTulach approved these changes

2022-08-10 08:42 UTC, JaroslavTulach commented
Once this PR is merged, we can also integrate the #3640 gate check.

2022-08-10 09:36 UTC, hubertp requested changes
So `self` in main is actually not needed, just need to change the way we invoke it. I will change it

2022-08-10 09:49 UTC, hubertp approved these changes

2022-08-10 13:31 UTC, merged