Component Browser with Grid View
enso-org/enso pull request #3766
Opened 2022-10-05 14:12 UTC by farmaazon

### Pull Request Description

This PR introduced overhauled Component List Panel implementation making use of the efficient EnsoGL grid view component. Also it delivers a couple of new features:
* A part of the new design: there are no more section headers in grid, instead groups are "glued" together. The local scope section is under "popular" (old "favorites").
* The keyboard management inside grid works.
* there is a mouse hover highlight
* selecting lowest entry in section when jumping with navigation bar.
* accepting input as-is with cmd/ctrl + Enter.

### Important Notes

**What is not implemented:**
* Focus management between panels. The grid is always focused. To accept the current input use ctrl+Enter shortcut.

**Known issues**
* the selection, especially in local scope section has some undesirable offset. The cause is known, but not so easy to fix.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

2022-10-06 14:52 UTC, wdanilo requested changes
A big chunk of a really nice code!

2022-10-06 14:52 UTC, wdanilo commented on app/gui/src/controller/searcher.rs
> +}
1. Why components provider needs access to breadcrumbs?
2. There is no explanation of what is "list" and what is "has_this_arg".

2022-10-06 14:52 UTC, wdanilo commented on app/gui/src/controller/searcher.rs
> +    }
`self.list` is not in RefCell, why don't we just return `&component::List` then?

2022-10-06 14:52 UTC, wdanilo commented on app/gui/src/controller/searcher.rs
> +        tracing::warn!("Previewing expression: \"{:?}\".", expression);
use `warn!` instead of `tracing::warn!`. Linter should warn about unnecessary qualification here

2022-10-06 14:52 UTC, wdanilo commented on app/gui/src/presenter/searcher/provider.rs
> +pub struct Component {
The title "=== Component ===" was placed 200 lines above this declaration. I feel that sections in this file can be structured better.

2022-10-06 14:52 UTC, wdanilo commented on app/gui/src/presenter/searcher/provider.rs
> +            }));
You don't need curly braces in these lambdas.

2022-10-06 14:52 UTC, wdanilo commented on app/gui/src/presenter/searcher/provider.rs
> +            // `entry_model` and `header_model`.
nice docs

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/Cargo.toml
> +num_enum = "0.5.1"
no nl

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/content.rs
> +    SubModules = 0,
Why are we using numbers for these enum variants? The mapping is not obvious to me.

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/content.rs
> +/// A information about group in column (not Local Scope group).
1. "aN information"
2. I dont understand these docs tbh - what do you mean by "no Local Scope group" and how is it related to previous part of the sentence?

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/content.rs
> +    pub original_height: usize,
Could you add some better description of what height and original_height are? I cant paint the picture in my head of what are the relations here and how these values depend on some filtered entries.

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/content.rs
> +    pub local_scope_size: usize,
I feel that if we need to create field docs, then the variables are probably wrongly named. Here, for example, groups is a list of groups arranged in columns. So maybe it should be named `columns`? Its type tells that these are columns of groups. The same applies to the second variable - based on the name `local_scope_size`, I'd never tell that it is "A number of entries in Local Scope section." – maybe we cna find a better name?

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/entry.rs
> +        variant: usize,
If we need to document this field, then IMO its name does not reflect ts purpose. Lets change it to `variant_index`.

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/entry.rs
> +    Custom(color::Rgba),
use `color::Lcha` and `color::Animation` everywhere instead

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/entry.rs
> +        };
this (and the rest of this function) code is pretty complex. I dont get the logic here (and I dont have to), but maybe it is possible to make it a little bit more clear?

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/layout.rs
> +        local_scope_entry_count: usize,
I havent seen const params in this codebase yet!

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/layout.rs
> +        assert_eq!(layout.location_of_element(header_of(5)), Some((1, RIGHT)));
could you add sections / descriptions of what corner cases these tests cover, please?

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/lib.rs
> +
spacing

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/lib.rs
> +    pub const CENTER: Col = 1;
1. why this is not computed?
2. What happens if I change it to 0?
3. What happens if I change the num of cols to 6?

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/lib.rs
> +                f!([model](loc) model.location_to_element_id(loc.as_ref()?))
no need for `[model]` here

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/grid/src/lib.rs
> +            grid.set_column_width <+ style.update.map(|s| (1, s.middle_column_width()));
what is this `1`?

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/src/lib.rs
> +            // let theme_path: style::Path = list_panel_theme::HERE.into();
commented code

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/src/lib.rs
> +        // selection_animation.set_spring.emit(spring);
todos left in the code

2022-10-06 14:52 UTC, wdanilo commented on app/gui/view/component-browser/component-list-panel/src/lib.rs
> +            //   component browser is visible
todos left in the code

2022-10-10 14:11 UTC, wdanilo approved these changes
Everything is cool - but I see one issue - on the video, when scrolling, the selection is jumping every second key press - is this a bug?

2022-10-10 16:05 UTC, akavel commented
@farmaazon See below for the first set of issues noticed during Acc/QA testing. The testing is expected to continue tomorrow.

### 1. Component List Panel contents blink when typing letters into the Expression Input panel.

*Steps to reproduce:*
 1. Create new project.
 2. Create new node.
 3. Type letter `a` into the Expression Input.
 4. Type letters: `b`, `l`, `e` into the Expression Input.

*Expected behavior:*
After a letter is typed into the Expression Input, the contents of the Component List Panel transitions to new contents either immediately, or with a smooth animation.

*Actual behavior:*
After a letter is typed into the Expression Input, the Component List Panel seems to show empty (white) contents momentarily, then quickly show correctly updated new contents. This looks jarring.

See the video below (**please disregard the ugly colors of the Component List Panel contents, this issue is already fixed in the PR**).

https://user-images.githubusercontent.com/273837/194875326-f0922f43-9ec7-4a9d-9223-e1ec2b49e019.mov


### 2. Impossible to scroll the Documentation Panel.

**Note:** This issue was already reported before. Fixing it might be covered by https://www.pivotaltracker.com/story/show/180872953 (to be confirmed).

*Steps to reproduce:*
 1. Create a new project.
 2. Create a new node.
 3. Navigate to the `read text` entry in the `Input` group of the Component List Panel by pressing the up arrow keyboard button 5 times.
     - Observe that a vertical scrollbar shows on the right of the Documentation Panel, suggesting that there is more to read than what is visible.
 4. Move the mouse to the area of the Documentation Panel and scroll up/down using the mouse wheel.

*Expected behavior:*
The mouse pointer is visible over the Documentation Panel contents. The contents of the Documentation Panel scroll up/down when using the mouse wheel.

*Actual behavior:*
The mouse pointer disappears underneath the Documentation Panel. The whole graph scrolls when using the mouse wheel.

See the video below (**please disregard the ugly colors of the Component List Panel contents, this issue is already fixed in the PR**).



https://user-images.githubusercontent.com/273837/194877926-151abf37-3649-4dd7-a042-f359c13408c6.mov

2022-10-11 10:12 UTC, farmaazon commented
> ### 1. Component List Panel contents blink when typing letters into the Expression Input panel.

Fixed.

> ### 2. Impossible to scroll the Documentation Panel.

Actually, it is possible, it only requires clicking on the panel. Perhaps it should auto select on hover, but it is more for US about new look of documentation panel.

2022-10-11 15:54 UTC, akavel commented
See below for some new issues noticed (apart from what was discussed with Adam during the day) and followups on the previous issues.

## Followups on previous issues.
1. Fixed.
2. Partly fixed (clicking with mouse in Doc Panel area allows scrolling), partly postponed to https://www.pivotaltracker.com/story/show/180872953 (showing the mouse cursor while it is in the Doc Panel area).

## New issues.

### 3. Poor UX after entering a module.

*Steps to reproduce:*
1. Create a new project and create a new node.
2. Click "ordering" module in "Base.Data" group in CB.

*Expected behavior:*
After entering a module, I would intuitively expect an entry of this module to be focused/highlighted, not an entry of its seemingly random sub-module. I would also expect the entries of the entered module to be shown in vivid colors, not grayed-out. It took me a *really* long while to think and understand what is the grayed out area and why it is grayed out, even knowing the code of the Component Browser and having implemented parts of it.

*Actual behavior:*
An entry of a sub-module of Base.Data is focused/highlighted. The entries of the Base.Data module look grayed-out.

See the screenshot below.

<img width="852" alt="Screenshot 2022-10-11 at 14 05 21" src="https://user-images.githubusercontent.com/273837/195085768-c8d8c470-5366-49d1-9eb5-f2bb8d35872c.png">


### 4. Design Doc Discrepancy: no "Type to search" label when Expression Input is empty.

The Design Doc in the section ["Search input"](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#search-input) notes:

> In case the input field [a.k.a. the Expression Input Panel] is empty, the label "Type to search" is visible. As soon as the user types the first character, the label should disappear. After removing all characters from the expression, the cursor should disappear and the label should appear again.

Such a label does not seem currently visible in the Component Browser's Expression Input Panel when the expression is empty.


### 5. Design Doc Discrepancy: When browsing a nested module, Favorites icon should be grayed out.

*Steps to reproduce:*
 1. Create a new project and create a new node.
 2. Click "ordering" module in "Base.Data" group in Component Browser.

*Expected:*
[Per the design doc](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#favorites-data-science-tools-section), the icon of the "Favorites Data Science Tools section" should be grayed out:

> If browsing other module than `All`, this section should not be displayed and its icon should be grayed-out.

*Actual:*
The "star" icon in the section navigator panel (left bar) looks the same as it looked before entering the module.


### 6. [non-blocker] Questionable UX: Navigating up from a module resets Active Focus to starting position.

*Steps to reproduce:*
 1. Create a new project and create a new node.
 2. Press the up arrow on the keyboard until the `vector` module in the `Base.Data` group is highlighted by the Active Focus.
 3. Press the Enter key.
 4. Press Shift-Enter three times to navigate back to the "All" top-level module of the Component Browser (or click the "All" name in the breadcrumbs).

*Actual:*
The bottom-most entry (`File read` in the `Input` group) in the middle column of the Component List Panel is highlighted by the Active Focus.

*Expected:*
It would feel more user-friendly to me if the `vector` module in the `Base.Data` group was highlighted by the Active Focus.

**NOTE:** This is a subjective opinion and is subject to discussion. The Design Doc does not seem to explicitly specify any behavior in this scenario. I don't see this as a blocker for merging the PR, but I believe it would be worth discussing as a possible improvement in the future.


### 7. When typed letters don't match any entry, pressing Tab inserts last matched entry.

*Steps to reproduce:*
 1. Create a new project and create a new node.
 2. Type `xuf` in the Expression Input Panel
     - Observe that the `Text utf 8` entry in the `Base.Data` group becomes highlighted by the Active Focus.
 4. Continue typing: type `z` in the Expression Input Panel.
     - Observe that the Component List Panel looks empty, with no item highlighted.
 5. Press the Tab key on the keyboard.

*Expected:*
The `xufz` text should be visible in the Expression Input Panel.

*Actual:*
The Expression Input Panel contains an `utf_8 ` expression.


### 8. Component Browser scroll position is not reset after accepting a local entry.

*Steps to reproduce:*
 1. Create a new project and create a new node.
 2. Navigate to the `main` entry in the Local section of the Component Browser using the arrow keys on the keyboard.
 3. Press Enter to accept the selection.
 4. Click the background of the Graph Editor to deselect the newly inserted `Main.main` node.
 5. Press Tab to start creating a new node.

*Expected:*
The Active Focus should highlight the bottom-most entry of the middle column in the Component List Panel. The Active Focus should be at the bottom of the Component List Panel. The contents of the Local section of the Component List Panel should not be visible.

*Actual:*
The contents of the Local section of the Component List Panel are visible. The Component Browser opens with the `main` entry in the Local scope highlighted with Active Focus, after which immediately the Active Focus moves with a smooth animation to the bottom-most entry of the middle column in the Popular section of the Component List Panel (see the screenshot below).

<img width="658" alt="Screenshot 2022-10-12 at 12 36 47" src="https://user-images.githubusercontent.com/273837/195321274-aeab6052-7705-42b4-9763-5962b7229438.png">


### 9. Warning with a message "Previewing expression: (...)" shows in the Dev Console.

*Steps to reproduce:*
 1. Create a new project.
 2. Open the Dev Console.
 3. Create a new node.

*Expected:*
No warnings in the Dev Console.

*Actual:*
A warning shows up in the Dev Console with the following message:
```
Previewing expression: ""read"".
```

2022-10-12 13:44 UTC, farmaazon commented
4 - https://www.pivotaltracker.com/story/show/183523678
5 - https://www.pivotaltracker.com/story/show/183523727
6 - I would wait if users start to complain about it
9 - fixed

I'm investigating the rest.

2022-10-12 14:32 UTC, farmaazon commented
7, 8, 9 - Fixed

2022-10-12 15:04 UTC, akavel commented
> 7, 8, 9 - Fixed

(7) does not look fixed.

Also, I don't seem to see a response to (3) - are you still working on it? The behavior seems still unchanged.

2022-10-13 10:40 UTC, akavel commented
After testing (7) a bit more, now I'm seeing a more complicated corner case:

### 10. After accepting a suggestion and erasing it, matching does not work correctly.

*Steps to reproduce:*
 1. Create a new project and create a new node.
 2. Type `xuf`.
     - Observe that `Text utf 8` entry in group `Base.Data` gets highlighted as an Active Focus Item.
 4. Press Tab key on the keyboard.
     - Observe that the `utf_8 ` text is now visible in the Expression Input Panel.
 5. Press Backspace key 6x (to erase the contents of the Expression Input Panel).
 6. Type `xufz`.

*Expected:*
The contents of the Component Browser List Panel should look empty, with no item highlighted as an Active Focus Item.

*Actual:*
A `main` entry is visible in the Component Browser List Panel (in the Locals section), and looks highlighted as an Active Focus Item (see the screenshot below). The Documentation Panel shows the documentation of the `main` entry. The error visualization preview shows an error message about `utf_8`. Pressing the Tab key on the keyboard results in the `Main.main ` text being inserted in the Expression Input Panel instead of the `xufz` text.

<img width="819" alt="Screenshot 2022-10-13 at 12 38 53" src="https://user-images.githubusercontent.com/273837/195575865-8c02f9eb-676f-41f9-9371-f07363ed054d.png">

2022-10-13 15:14 UTC, akavel commented
### 11. Composing an expression can get Component Builder into defunct state.

*Steps to reproduce:*
 1. Create a new project and a new node.
 2. Type `able` and press Tab key on the keyboard.
     - Observe expression `from_rows` in the Expression Input panel.
     - Observe that the entries in the Component List Panel are now filtered by return type, and only entries returning a Table are visible.
 3. Using the arrow keys on the keyboard, navigate to the `Geo.point` entry in the Component List Panel, then press Tab key on the keyboard.
     - Observe expression `from_rows Geo.point` in the Expression Input Panel.
 4. Type ' 0 0 0' in the Expression Input Panel.
     - The whole expression should now be: `from_rows Geo.point 0 0 0`.
 5. Press Cmd+Enter to accept the custom expression.

*Expected:*
A node with the specified expression is created. Text editing cursor disappears.

*Actual:*
A node with the specified expression is created. A blinking text cursor is still visible inside the node. Typing text results in text being appended to the already created node. Opening the Component Browser to create a new node and entering text into it results in text being appended to the first node's expression as well.

2022-10-13 15:47 UTC, akavel commented
Issue (11) does not seem to reproduce on @farmaazon's machine, so we decided to ignore it for now. Other issues seem fixed or explicitly postponed to new Pivotal tasks. I thus consider Acceptance/QA as **Passed**.

2022-10-14 10:43 UTC, merged