use share-generics rustflag to improve compile times
enso-org/enso pull request #3838
Opened 2022-10-31 12:37 UTC by Frizi

### Pull Request Description

Add `-Zshare-generics=y` to our `RUSTFLAGS`. This improves build times significantly, especially for our crates with slowest builds. That means there is a noticeable build time decrease when modifying dependencies of those crates.

Timings of full build (including all dependenceis) on my machine:
- Without `share-generics`: total time 12m 25s
- With `share-generics`: total time 11m 5s

Comparsion of compile timings for downstream crates, left graph is with the new flag:
![image](https://user-images.githubusercontent.com/919491/199008622-35b46ad0-826c-4bdc-9e55-f43a48d250e5.png)

### Important Notes

This is an unstable option. We are using nightly everywhere, so this shouldn't be a problem, but it might add some instability in the future.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

2022-10-31 13:57 UTC, mwu-tow approved these changes
Looks good.

Just one question: are we certain that this does not affect performance negatively? IIRC I've heard somewhere that this flag could interfere with cross-crate inlining of generics.

2022-10-31 14:37 UTC, Frizi commented
I am not 100% sure about that. I know that this option tends to lead to smaller code size. As for performance, it changes the behaviour of generics to not always be treated as `#[inline]`. Given that our runtime is currently dominated by shader compilation, malloc and memcpy, I doubt that it will have any noticeable effect. I wasn't able to notice any difference, but more rigorous performance measurements would be needed to be absolutely sure.

2022-10-31 18:06 UTC, Frizi commented
It's interesting. With `share-generics` the code is certainly less inlined. I can see more precise calls in callstacks, e.g. it's clear that nalgebra matrix multiplication dominates the frame time when camera moves around. When the flag is disabled, all that time is associated with `tracing::span::Span::in_scope`, which is the first non-inlined call for that case. It still takes pretty much the same time. In fact, the frame times of the exact same scene seems to be slightly lower when the flag is enabled, but the variance is still high so it's hard to compare definitely. I am pretty confident that it won't hurt though. If it is ever a problem, we can easily remove the flag.

There is also some benefit to smaller `ide.wasm` size:
| | release build | release + wasm-opt |
|---|---|---|
| no change | 54980 KiB |  41817 KiB |
| `share-generics=y` | 42410 KiB | 34137 KiB | |


That means this change can actually give us slightly easier to understand profiles and smaller code size without much downside, as far as I can tell.

2022-10-31 20:05 UTC, wdanilo requested changes
/I disagree that lowering the performance around matrix multiplication is not an issue. Rendering performance is very important to us and we need to optimise it heavily, especially for weaker hardware. Also, I disagree with the term "Given that our runtime is currently dominated by shader compilation [...]". Shader compilation happens ONCE, while matrix computations happens constantly. I am OK with putting this flag in a debug mode - watch script, when compiled without optimisations, but the optimised build should not use it. I am also against the approach "let's sacrifice the performance here because its not a dominating factor". We have some performance issues and lowering performance anywhere, esecially affecting the rendering performance is a no-go for me.

2022-11-01 09:37 UTC, Frizi commented
@wdanilo This is not what I said. This didn't lower the performance of rendering. All it did is to show it more precisely in the callstack, but the time it takes is still the same. The measurements I took into account were after all shader compilation is done, so I needlessly mentioned that. The memcpy/malloc thing is still relevant though - it's the next thing on the list after matrix multiplication and this change doesn't affect that.

The end product is much less code overall, because the same generic functions don't get compiled and embedded into the binary multiple times. That would happen just the same if you compiled everything as a single crate, but that of course won't ever be the case. Less code is a win on multiple fronts for us, it will transfer faster, compile faster on the client and run faster in some cases as well.

Inlining isn't always good. I'd rather leave it up to the compiler to decide when it's worth it most of the time. This flag allows the compiler to do that decision, because the generated code from generics isn't duplicated that much. If we have a good reason to force inline any particular call, you can always add `#[inline]` or even `#[inline(force)]` to your generic method and it will work just fine.

2022-11-01 12:45 UTC, wdanilo commented
@Frizi:
1. `but the time it takes is still the same` - how did you measure it?
2. The memcpy/malloc thing is not relevant IMO. Yes, sure, we might want to improve it, but it should not affect our decision of decreasing performance in other part of the code.
3. `The memcpy/malloc thing is still relevant though` - yes, but it is also a bad thing. If the matrix multiplications functions are not inlined / specialised as they were, this will affect the performance.
4. `BTW, this flag is enabled by default in rustc if you use -O1 or -Os or -Oz` - but it is not enabled by default in -O2 for some reasons. So I would not enable it in our optimised build. Howeverr, this is even more interesting - our debug builds are not using -O2, so why this flag was not enabled by default here?

2022-11-01 14:03 UTC, Frizi commented
I was measuring it with chrome performance devtools, but I have seen a lot of variance overall.

I have measured it again after CPU upgrade and now the variance is way smaller. it is clear that this has some performance overhead and the bulk of it is in matrix multiplication.

Left - no changes, right - `share-generics`.
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/919491/199248631-fb78dff9-8e9c-4f64-87bd-d85c2c7c4a5a.png">

I took the screenshots of worst-case frames on both sides that I was able to find in the profile. This is measuring a scene with component browser opened and panning the camera.

| | total task time | mousemove (camera update) | animation frame time |
|-|-|-|-|
| no change | 2.73ms | 0.31ms | 1.97ms |
| `share-generics=y` | 3.67ms | 0.87ms | 2.19ms |.

The worst case total time difference is roughly representative of average relative differences across all frames. They vary up to around 0.5ms. Though the exact split of mousemove/animation frame has more variance.

I agree that this is not a good thing to enable right now for release builds, but it's worth considering the file size reduction as as performance win as well. We might want to reevaluate that later once the code is more performant in general.

It would be really good to enable it in dev builds though. I'm currently not using dev builds, because the lack of any optimization makes them unbearably slow at runtime (we use `opt-level = 0`). We could potentially enable `opt-level = 1` and benefit from this as well.

2022-11-01 14:11 UTC, wdanilo commented
1. Measuring that with dev tools is not precise.
2. First you claimed that `This didn't lower the performance of rendering`, now you're saying `it is clear that this has some performance overhead.`. I have a pretty big problem with this. If we are communicating a sentence, like "this does not lower the performance", I need to be sure that such statements were checked and proven. You can write "I THINK this does not lower the performance", but if you state it as you did, this has to be properly checked before making such statements. I'm raising this, as this is a very important aspect of working in a team, especially on a performance-critical parts.
3. "unbearably slow at runtime" is not clear. What do you mean by that? Could you please provide information at least about the FPS you've got? But not from chrome dev tools, it affects the performance drastically. Use our FPS meter instead.
4. Getting back to solution - this affects the performance of the rendering loop, we should not enable this on optimised builds.

2022-11-01 14:27 UTC, Frizi commented
> If we are communicating a sentence, like "this does not lower the performance", I need to be sure that such statements were checked and proven. You can write "I THINK this does not lower the performance", but if you state it as you did, this has to be properly checked before making such statements. I'm raising this, as this is a very important aspect of working in a team, especially on a performance-critical parts.

I get that, that was an oversimplification on my part. I was briefly repeating what I said in previous comment, where the sentiment is that the situation is not super clear. With new hardware (that I got running just today) I was able to get more trustworthy data, so I posted it and changed my judgement on it as well.

> "unbearably slow at runtime" is not clear. What do you mean by that?
By that I mean that the page load time is very slow. It's not about FPS, but about the time from refresh to interaction. It takes above minute for me to load very simple graph. It's really important for me to lower that time as much as possible, and that usually require some form of optimization at build time.

> Measuring that with dev tools is not precise.
Can you give me more information about that? I know that the measurement is done by stack sampling, so it isn't the most accurate in every individual instance, but it is also very low-overhead way of measuring it and gives you good overview where the time is likely spent.

2022-11-02 16:46 UTC, closed without merging