Another attempt at M1 compilation
enso-org/enso pull request #3859
Opened 2022-11-08 15:04 UTC by kustosz

### Pull Request Description

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

2022-11-08 15:41 UTC, JaroslavTulach approved these changes
Thanks a lot Marcin, I have just confirmed myself that your changes work well on my Intel based Mac. Please integrate as soon as possible. Otherwise integration of #3611 breaks all developers compiling on Mac M1.

2022-11-08 15:41 UTC, JaroslavTulach commented on build.sbt
> +        "--out-dir",
That's good idea to share the output dir!

2022-11-08 15:41 UTC, JaroslavTulach commented on project/DistributionPackage.scala
> -    val dir = if (isMac) {
Thanks for this simplification. I hope it works!

2022-11-08 16:00 UTC, hubertp requested changes
Try to use sbt's setting rather than hardcoding the target path in various places

2022-11-08 16:00 UTC, hubertp commented on build.sbt
> +        "target/rust/debug"
This shouldn't be hard-coded. Instead one should use the value of the output target setting.

2022-11-08 16:00 UTC, hubertp commented on lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
> +      if (!searchFromDirToTop(e, root, "target", "rust", "debug", name)) {
Similarly as in the other case, those shouldn't be hardcoded.

2022-11-08 16:00 UTC, hubertp commented on project/DistributionPackage.scala
> +    val dir = "target/rust/debug/"
This  value should be provided from the outside, hard-coding this is probably a bad idea

2022-11-09 10:12 UTC, hubertp commented on lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
> +      if (!searchFromDirToTop(e, root, "target", "rust", "debug", name)) {
OK, this is in static initializer so it will be hard to configure. Note that the `debug` bit is probably gonna be problematic for non-dev releases

2022-11-09 10:15 UTC, hubertp approved these changes
@kustosz pushed my change with SettingsKey to illustrate what I had in my mind when talking about hardcoded values. Hope you don't mind

2022-11-09 15:26 UTC, merged