Make a VCS save on ctrl+s shortcut
enso-org/enso pull request #3923
Opened 2022-11-28 08:39 UTC by galin-enso

### Pull Request Description

Save a snapshot of the project directory to the VCS on `ctrl+s`. If the operation fails because the VCS was not initialized previously, it will try to initialize the VCS first and then save a snapshot.

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

2022-11-28 13:03 UTC, wdanilo approved these changes
Approve from my side, but someone knowing our backend should check it as well :)

2022-11-28 14:41 UTC, farmaazon requested changes

2022-11-28 14:41 UTC, farmaazon commented on app/gui/src/controller/text.rs
> +            response?;
1. This method should be a part of the Project controller, as we no longer saving a single text file.
2. Please add a test for this method, mocking the communication with the engine. See other similar tests for reference.

2022-11-28 14:41 UTC, farmaazon commented on app/gui/src/presenter/code.rs
> +    fn save_module(&self) {
Again, we do not save a module here, instead store a new save of the entire project.

This method shall be defined and used in the project presenter.

2022-12-01 08:50 UTC, farmaazon approved these changes

2022-12-01 14:07 UTC, hubertp reviewed
So if someone wants to save a project with a particular name, that's gonna be a different operation?

2022-12-01 14:07 UTC, hubertp commented on app/gui/src/controller/project.rs
> +                if error_code == code::FILE_NOT_FOUND {
Oh, this is FILE_NOT_FOUND? I need to change that so that it returns `VCSNotFound`.. sorry!

2022-12-01 16:31 UTC, galin-enso commented
> So if someone wants to save a project with a particular name, that's gonna be a different operation?

Do you mean the `ctrl+s` shortcut being used to perform for example a whole project folder save in another location (instead of storing a project snapshot to the VCS as is implemented here)? Or having named VCS snapshots, not just time-stamped commit messages?

2022-12-01 16:41 UTC, hubertp commented
> > So if someone wants to save a project with a particular name, that's gonna be a different operation?
> 
> Do you mean the `ctrl+s` shortcut being used to perform for example a whole project folder save in another location (instead of storing a project snapshot to the VCS as is implemented here)? Or having named VCS snapshots, not just time-stamped commit messages?

The latter. I suppose there will be a follow up (`vcs/save` takes an optional name), right?

2022-12-01 16:59 UTC, galin-enso commented
> The latter. I suppose there will be a follow up (`vcs/save` takes an optional name), right?

Ok, yes. If I understand correctly the first step is to implement basic snapshot/restore functionality, which can be expanded to named snapshots later.

2022-12-02 11:58 UTC, farmaazon commented
QA process passed, have a nice day!

2022-12-02 12:39 UTC, merged