Implement SKIP/FREEZE in parser/TreeToIr
enso-org/enso pull request #3942
Opened 2022-12-01 23:49 UTC by kazcw

### Pull Request Description

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

2022-12-08 23:46 UTC, wdanilo requested changes
I was sure we agreed to implement it as a macro in the parser. Let's have a chat about it pls.

2022-12-08 23:46 UTC, wdanilo commented on engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
> +                when "FREEZE".equals(app.getSegments().get(0).getHeader().codeRepr()) ->
These strings are used in several places, let's refactor them to constants.

2022-12-13 08:58 UTC, JaroslavTulach approved these changes

2022-12-20 11:46 UTC, wdanilo approved these changes

2022-12-20 17:33 UTC, merged