AST support for new annotation syntax
enso-org/enso pull request #4018
Opened 2023-01-02 22:18 UTC by kazcw

### Pull Request Description

Implement new annotation syntax.

See: https://www.pivotaltracker.com/story/show/184132200

### Important Notes

- This includes only AST/parser frontend support; the new `Annotated` type needs to be handled in `TreeToIr`.

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

2023-01-03 08:13 UTC, wdanilo requested changes
❤️

2023-01-03 08:13 UTC, wdanilo approved these changes
Ouch, I meant approve: ❤️

2023-01-04 08:42 UTC, JaroslavTulach approved these changes

2023-01-04 08:46 UTC, hubertp approved these changes

2023-01-04 17:50 UTC, merged