[DRAFT] feat(183351503): Add authentication via AWS Cognito (inc. GitHub + Google + Email/Password)
enso-org/enso pull request #4041
Opened 2023-01-12 05:23 UTC by indiv0

### Pull Request Description

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

2023-01-25 18:17 UTC, wdanilo commented
1. Did we update some dependencies that package lock has 40k+ changed lines? If so, what deps were updated?
2. Waiting for videos, ping me when they will be here.

2023-01-27 06:09 UTC, indiv0 commented
> 1. Did we update some dependencies that package lock has 40k+ changed lines? If so, what deps were updated?
> 
>     2. Waiting for videos, ping me when they will be here.

We added some new dependencies but I don't think any were updated... I'll double check and/or regen the package-lock.json to see why the diff is so large.

Videos have been added. @wdanilo

2023-01-31 06:41 UTC, wdanilo requested changes
This code is not linted and not commented. Also, we need to chat aobut how to integrate it properly.

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +            Electron.app.setAsDefaultProtocolClient('enso')
literals not refactored to a common place

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +            if (process.argv.length >= 2) {
magic - can you please refactor it to a well named variable?

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +            // custom urls. For macOS 'open-url' event is emitted
no dot

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +                // Someone tried to run a second instance, we should focus our window.
what is "our" window and second instance of what?

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +                console.log('second-instance', commandLine, workingDirectory)
this looks like a debuglog

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +    console.log('open-url', event, url)
debug log

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/content/esbuild-config.ts
> +        'src/wasm_imports.js'
I believe we should strucutre itidfferent way around,  lets chat tomorrow

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/content/src/amplify.js
> +// =====================
1. Use typescript
2. Use eslint-compatible docs for typescript in all files

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/content/src/confirmation.html
> +<!DOCTYPE html>
this file name is enigmatic. What is `content/confirmation`? Is this a confirmation of content of the app?

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/content/src/confirmation.ts
> +import { Auth } from "aws-amplify"
1. no docs here and in other places
2. no sections

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/content/src/confirmation.ts
> +// FIXME [NP]: make this an async function
fixmes left

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/content/src/forgot_password.html
> +                      <path d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207" />
This is magic - what is this?

2023-01-31 06:41 UTC, wdanilo commented on app/ide-desktop/lib/content/src/forgot_password.html
> +                      <path d="M13 9l3 3m0 0l-3 3m3-3H8m13 0a9 9 0 11-18 0 9 9 0 0118 0z" />
magic again, and again below

2023-01-31 16:24 UTC, wdanilo commented on app/ide-desktop/lib/client/electron-builder-config.ts
> +        { name: 'Enso URL', schemes: ['enso'], role: 'Editor' }
Product name repetition

2023-01-31 16:26 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +    console.log(`${event} target`, target.href)
debug log

2023-01-31 16:28 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +    console.log('Welcome Back', `You arrived from: ${url}`)
If this is a log, it sohuld not tell to the user "Welcome" etc - these are logs

2023-01-31 16:28 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +    } catch {}
emty catch

2023-01-31 16:29 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +    }
no docs why

2023-01-31 16:29 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +        const gotTheLock = Electron.app.requestSingleInstanceLock()
no info whati t does

2023-01-31 16:29 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +            Electron.app.quit()
no info why

2023-01-31 16:30 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +                // Someone tried to run a second instance, we should focus our window.
We should allow for 2 instances of the app

2023-01-31 16:31 UTC, wdanilo commented on app/ide-desktop/lib/client/src/index.js
> +            console.log('Server.create', serverCfg)
debug log

2023-01-31 16:32 UTC, wdanilo commented on app/ide-desktop/lib/client/src/preload.cjs
> +// Open URLs in external browser
no dot + no good explanation what t. really does

2023-01-31 16:39 UTC, wdanilo commented on app/ide-desktop/lib/content/esbuild-config.ts
> +    path.resolve(thisPath, 'src', 'reset_password.html'),
Lets stay only with single `index.html` please

2023-01-31 16:41 UTC, wdanilo commented on app/ide-desktop/lib/content/esbuild-config.ts
> +        'src/wasm_imports.js'
make it one entry point, not in `content`, and dont use custom `esbuild config`.

2023-01-31 16:42 UTC, wdanilo commented on app/ide-desktop/lib/content/src/amplify.js
> +const USER_POOL_WEB_CLIENT_ID = process.env.NEXT_PUBLIC_AUTH_USER_POOL_WEB_CLIENT_ID || '7vic1uoogbq4aq2rve897j0ep0'
7vic1uoogbq4aq2rve897j0ep0 - magic

2023-01-31 16:44 UTC, wdanilo commented on app/ide-desktop/lib/content/src/index.ts
> -    }
why?

2023-01-31 16:46 UTC, wdanilo commented on app/ide-desktop/lib/content/src/registration.ts
> +    console.log('REGISTRATION Auth configured')
debug logs

2023-01-31 16:47 UTC, wdanilo commented on app/ide-desktop/lib/content/src/reset_password.ts
> +if (submitButton === null) { throw new Error('submitButton is null') }
1. Top level code - it sohuld go to a function, like main or whatever

2023-01-31 16:49 UTC, wdanilo commented on app/ide-desktop/lib/content/src/reset_password.ts
> +}
also, run `npx tsc --noEmit` to check for type errors.

2023-01-31 16:49 UTC, wdanilo commented on app/ide-desktop/lib/content/src/reset_password.ts
> +async function resetPassword(e: MouseEvent, email: string, code: string, newPassword: string) {
var names `e` -> `event`, in other places as well pls

2023-02-27 11:47 UTC, closed without merging

2023-02-27 11:54 UTC, indiv0 commented
Closed in favour of https://github.com/enso-org/enso/pull/5716