Fix visualisation sometimes no opening with space bar.
enso-org/enso pull request #5624
Opened 2023-02-10 15:33 UTC by MichaelMauderer

### Pull Request Description

Visualizations closing right after opening was caused by the GUI being unresponsive during loading of some visualizations. This caused the timer for measuring the time between space bar press and space bar release to be inflated. The delayed events triggered the "visualization preview mode”, thus closing the visualization has it seemed that the space bar was held down, even though the events just arrived with some delay. 

The problem is mitigated by considering the number of frames that have passed between the space and down and the space bar up event, instead of just the wall clock time. If the number of frames is too low, this indicates that frames were dropped to the time is inflated. 

Fixes https://github.com/enso-org/enso/issues/5223

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

2023-02-10 15:57 UTC, kazcw requested changes

2023-02-10 15:57 UTC, kazcw commented on lib/rust/web/src/lib.rs
> +        let closure_handle_internal = Rc::clone(&closure_handle);
Is there a memory leak here? The closure strongly-references the closure handle, which owns the closure.

2023-02-10 15:57 UTC, kazcw commented on lib/rust/web/src/lib.rs
> +/// A counter that counts frames thr frames that have passed since its initialization.
Typo

2023-02-13 09:56 UTC, farmaazon approved these changes
Please address the leak issue by @kazcw

2023-02-13 09:56 UTC, farmaazon commented on app/gui/view/graph-editor/src/lib.rs
> +const VIZ_PREVIEW_MODE_TOGGLE_FRAMES: i32 = (VIZ_PREVIEW_MODE_TOGGLE_TIME_MS / 16.0) as i32;
If we assume 60 FPS I would rather put here 1000.0/60.0. Or make assumed FPS another constant

2023-02-13 15:00 UTC, wdanilo requested changes
I need a better explanation of why this PR works and what was the cause that visualizations were disappearing. The code is probably fine, but it should explain itself for future readers

2023-02-13 15:00 UTC, wdanilo commented on app/gui/view/graph-editor/src/lib.rs
> +/// `VIZ_PREVIEW_MODE_TOGGLE_TIME_MS` interval. Assumes 60fps.
This lacks documentation of what these constants do. Please add docs to previous constant as well. Also, the explanation `Number of frames we expect to pass during the...` doesn't really explain what it means and what it is used for.

2023-02-13 15:00 UTC, wdanilo commented on app/gui/view/graph-editor/src/lib.rs
> +        // dropped frames during the visualisation initialisation.
What does it mean? What is "too much time"? There is no explanation why this code exists and what it really does.

2023-02-13 16:19 UTC, MichaelMauderer commented
> I need a better explanation of why this PR works and what was the cause that visualizations were disappearing. The code is probably fine, but it should explain itself for future readers

The problem here is, that we are trying to measure the time between the key down and the key up event. If the key up event happens before the `VIZ_PREVIEW_MODE_TOGGLE_TIME_MS` has passed, we consider it a normal key press that opens the visualization. If the key up event happens after `VIZ_PREVIEW_MODE_TOGGLE_TIME_MS` has passed, we assume that a "press and hold” action was performed, which would trigger our visualization preview and thus the visualization should be closed when the key is release. But if the opening of the visualization takes a lot of time, specifically, longer than `VIZ_PREVIEW_MODE_TOGGLE_TIME_MS`, then the key up event will be processed too late, even if the key was already released right after the key down. We can guard against this by not just measuring the time, but checking that enough frames have passed. Since if we take too much time processing things, we get dropped frames. 

I'll now update the docs to make this clearer.

2023-02-15 11:19 UTC, wdanilo approved these changes
Perfect, now it is fully understandable, thanks!

2023-02-15 11:44 UTC, MichaelMauderer commented
@kazcw Could you also re-review tour requested changes?

2023-02-16 15:17 UTC, kazcw approved these changes

2023-02-16 17:26 UTC, vitvakatu approved these changes
QA passed

2023-02-17 11:33 UTC, merged