Update system requirements of CONTRIBUTING documents
enso-org/enso pull request #5682
Opened 2023-02-17 13:41 UTC by Nctdt

### Pull Request Description
Older versions of `Powershell (5.x)` do not support running the `run` command, so you need to replace it with a higher version of `Powershell (7.x)` or use `cmd`

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

2023-02-17 13:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/enso-org/enso?pullRequest=5682) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/enso-org/enso?pullRequest=5682) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/enso-org/enso?pullRequest=5682) it.</sub>

2023-02-17 13:58 UTC, PabloBuchu approved these changes

2023-02-20 10:04 UTC, jdunkerley requested changes
Small tweak to wrap at 80 characters.

2023-02-20 10:04 UTC, jdunkerley commented on docs/CONTRIBUTING.md
> +- On Windows, the `run` command must be run in the latest version of `Powershell` or in `cmd`.
```suggestion
- On Windows, the `run` command must be run in the latest version of
  `Powershell` or in `cmd`.
```

2023-02-24 13:58 UTC, jdunkerley approved these changes

2023-02-25 05:49 UTC, merged