Don't let the IDE throw away executionContext/executionStatus messages
enso-org/enso pull request #5734
Opened 2023-02-22 10:51 UTC by JaroslavTulach

### Pull Request Description

IDE currently completely ignores `executionContext/executionStatus` messages without giving user any clue - even if the reported status signals an error.

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

2023-02-22 10:57 UTC, farmaazon commented on app/gui/src/model/project.rs
> +    },
It's not needed, we already have such notifications in https://github.com/enso-org/enso/blob/20149c19bb0835cb0456dba3a548c125840c409a/app/gui/src/controller/ide.rs#L35

2023-02-22 11:20 UTC, farmaazon requested changes
I think sometimes this solution can rather confuse user than help him:
1. The errors reported in the execution status are still not displayed if warning happens to be first on the list
2. We do not inform the user about the place where error is produced. Theoretically it could be in the different file

Overall, I'd prefer to implement #5201 first, then make it properly: display a message with details section, and in details print all the information we get in executionStatus message.

The error log could remain. But then, let's print errors for all messages.

2023-02-28 09:41 UTC, jdunkerley commented
Blocked until #5728 is completed, but should be done before design partners release.

2023-03-09 09:21 UTC, JaroslavTulach commented
Original problem addressed by #5794. Closing.

2023-03-09 09:21 UTC, closed without merging