Feat: Tool tip support for larger values in Table visualization
enso-org/enso pull request #6009
Opened 2023-03-20 12:21 UTC by Nctdt

### Pull Request Description
Fixes #5968
When the content exceeds the width and causes additional content to be displayed as "...", hovering the mouse for one second will use a tooltip to display all the content.

![1679314293639](https://user-images.githubusercontent.com/52877578/226336687-8dd75578-979e-4019-94f9-aab1c3d98e5c.jpg)
![1679314316214](https://user-images.githubusercontent.com/52877578/226336697-d1f15b71-5af7-4ca0-af52-c2441934faf1.jpg)
![1679314326304](https://user-images.githubusercontent.com/52877578/226336704-f0f7a8cb-ac2d-49d7-836c-0accd2bf1163.jpg)

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-03-21 02:43 UTC, wdanilo reviewed
How does it look with really long text, e.g. one that doesn't fit in one line? Also, how does it look like with text that has many lines, eg. 1000?

2023-03-21 14:30 UTC, Nctdt commented
> How does it look with really long text, e.g. one that doesn't fit in one line? Also, how does it look like with text that has many lines, eg. 1000?

Displaying all the content can make it very long, but this can be resolved by reducing the displayed content, such as reducing it to a single line or 100 characters or less. What do you think?

2023-03-22 00:01 UTC, wdanilo commented
> > How does it look with really long text, e.g. one that doesn't fit in one line? Also, how does it look like with text that has many lines, eg. 1000?
> 
> Displaying all the content can make it very long, but this can be resolved by reducing the displayed content, such as reducing it to a single line or 100 characters or less. How do you think it should be handled?

We should show the user as much info as possible. So the popup should wrap the data and should display as much as possible there in multiple lines. Basically, the more data user is able to preview, the better. Also, @sylwiabr, @NedHarding, and @jdunkerley, what if the multiline preview is not enough? Should the preview be scrollable?

2023-03-23 13:47 UTC, sylwiabr commented
I don't think we need a scrollable preview in a tooltip.

2023-03-23 14:43 UTC, Nctdt commented
My idea is to truncate the string to 50 characters and display ${str.slice(0, 50)}... if it exceeds the limit. What do you think, @wdanilo ?

2023-03-27 21:26 UTC, wdanilo commented
If we could at least show long string broken into several lines (like 4-5 lines) that would be amazing. Then, sure, let's just skip rest of the string and add `...` at the end to show the user that there is more. Ok? :)

2023-03-28 02:47 UTC, NedHarding commented
> 

This gets so tricky and subtle.  What if the string ends in "..."?  Its always a good plan to use some other color/symbol to make meta information like the string being truncated separate than the data itself.  This is true both in the grid and in the tooltip version of the display, which presumably truncate at different lengths.  

Also, it is really important for a user to be able to explore the entirety of the data.  The simplest way this can be accomplished is to allow copy to the clipboard to get the full text.  But then you are asking the user to switch to external software to analyze their data - so they (the user) might question why they are using enso and not the other program they had to switch to?

And we have to remember, really long values are **really** common.  It is not an exceptional case at all.

2023-03-28 02:58 UTC, wdanilo commented
I totally agree with @NedHarding, that's why I proposed scrolling the values in popups. Copy-pasting them to another tools looks like a really bad solution, while scroll would solve all issues here.

2023-03-28 03:05 UTC, NedHarding commented
I mostly agree with @wdanilo - except the tooltip part.  Scrollbars and selection for copy/paste are much easier with a persistent control instead of a tooltip.  Tooltips have this difficult habit of going away if you move the mouse wrong.  To effectively browse a large field and scroll and potentially copy a selection, it would be better served by a text box that is accessed by a double click on a value and then it shows below/right or on top of grid and has to be actively dismissed.  This also makes a keyboard interface more intuitive (enter or space) where tooltips are typically mouse only.

2023-03-28 03:06 UTC, wdanilo commented
Oh, thats exactly what I meant by tooltip. You are right, my terminology was wrong. Thanks for catching it and explaining it so clearly!

2023-03-28 03:20 UTC, NedHarding commented
@wdanilo I should add - there still needs to be some maximum to avoid crashing the GUI.  It is very easy to construct a value with >4GB for instance which we would not want to load in memory.  So even with scrolling, we should cap at 1MB or something sane for a text control.

2023-03-30 10:31 UTC, jdunkerley requested changes

2023-03-30 10:31 UTC, jdunkerley commented on app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
> +                enableRangeSelection: true,
This will result in warnings in the console if not running against "Enterprise" AG Grid.

2023-04-06 11:13 UTC, PabloBuchu commented
@Nctdt whats the status of this PR? When you can address all the issues?

2023-04-11 11:20 UTC, Nctdt commented
> @Nctdt whats the status of this PR? When you can address all the issues?

I'm sorry, I cannot solve these problems.

2023-05-30 08:34 UTC, farmaazon commented
@PabloBuchu @Nctdt What are the action points?

If the problems are unsolvable, can we close this PR?

2023-05-30 09:15 UTC, jdunkerley commented
Lets close for now - we have a different approach suggested by @NedHarding which we will implement in the future.

2023-05-30 09:40 UTC, closed without merging

2024-02-23 14:25 UTC, farmaazon commented on app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
> +                enableRangeSelection: true,
@jdunkerley we use enterprise AGGrid now, don't we? So perhaps we could resurrect this PR and move changes to Table Vis in GUI2?