Fix prettier config; run prettier
enso-org/enso pull request #6132
Opened 2023-03-29 12:34 UTC by somebody1234

### Pull Request Description

Does the same thing as #6003, which was merged but reverted due to issues when running with `-authentication=true`.

- Fixes prettier config to include `.tsx`
- `prettier -w .` has been run in `app/ide-desktop`

### Important Notes
After this is merged, a PR SHOULD be created to add the following file to the root directory:
`.git-blame-ignore-revs`
```
# <name of the commit for this PR>
<hash of the commit for this PR>
```
This makes `git blame` ignore the commit, which is a good idea since this PR only does formatting changes.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-03-30 09:52 UTC, PabloBuchu commented
@somebody1234 This PR looks totally harmelss but I am getting really weird errors from time to time. Yesterday there was problem with `GL_INVALID_FRAMEBUFFER_OPERATION` it is not occuring anymore but I am getting problems with connecting to project manager after signing in. It's not deterministic (it's not happening all the time). I wasn't able to reproduce it on develop.. 


<img width="1380" alt="Screenshot 2023-03-30 at 11 46 07" src="https://user-images.githubusercontent.com/2855109/228798121-722da86c-ebfa-4e01-89dd-1a3023f6cdf8.png">

<img width="1206" alt="Screenshot 2023-03-30 at 11 46 23" src="https://user-images.githubusercontent.com/2855109/228798113-3cdbb361-9629-4f86-9abb-d84979158db2.png">

2023-03-30 09:54 UTC, PabloBuchu requested changes
see the comment with screenshots

2023-03-30 10:09 UTC, PabloBuchu commented
also @indiv0 can you try and reproduce my errors?

2023-03-30 11:49 UTC, indiv0 commented
Reproduced **an issue** but not the same issue. Also on `./run ide build` and running from `dist` with `-authentication=true`:

Occurred on the first attempt to launch the process. But it's not the same error so I'm not sure if it's related.

<img width="1383" alt="Screenshot 2023-03-30 at 13 47 17" src="https://user-images.githubusercontent.com/641547/228826432-acbaa9fd-d1bc-4953-9df6-80b567e7333d.png">

<summary>
<details>
<pre>
<code>
panicked at 'Trying to override uniform 'pixel_ratio'.', lib/rust/ensogl/core/src/system/gpu/data/uniform.rs:78:13

Stack:

Error
    at eval (eval at <anonymous> (http://localhost:8080/index.js:74:5709), <anonymous>:17796:19)
    at logError (eval at <anonymous> (http://localhost:8080/index.js:74:5709), <anonymous>:16936:14)
    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8080/index.js:74:5709), <anonymous>:17795:12)
    at console_error_panic_hook::Error::new::h2ccfe1f2d233bd00 (http://localhost:8080/pkg-opt.wasm:wasm-function[414140]:0x4d71f87)
    at console_error_panic_hook::format_panic_impl::h76c87aa6d4b4a46d (http://localhost:8080/pkg-opt.wasm:wasm-function[85066]:0x2d3c542)
    at console_error_panic_hook::format_panic::h2e7061ff70bb7ee4 (http://localhost:8080/pkg-opt.wasm:wasm-function[473515]:0x4e523b2)
    at enso_web::report_panic::h7a6e782d87be6945 (http://localhost:8080/pkg-opt.wasm:wasm-function[19467]:0x196e7e3)
    at core::ops::function::Fn::call::hf0e324b77f56f9d9 (http://localhost:8080/pkg-opt.wasm:wasm-function[328945]:0x4a9d674)
    at std::panicking::rust_panic_with_hook::hdc43d6b15c221d2e (http://localhost:8080/pkg-opt.wasm:wasm-function[92381]:0x2ebc220)
    at std::panicking::begin_panic_handler::{{closure}}::h138701bc4f366007 (http://localhost:8080/pkg-opt.wasm:wasm-function[150559]:0x3914856)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h6a334029ca520246 (http://localhost:8080/pkg-opt.wasm:wasm-function[340054]:0x4b306cc)
    at rust_begin_unwind (http://localhost:8080/pkg-opt.wasm:wasm-function[280602]:0x4768c3f)
    at core::panicking::panic_fmt::hfb8e3b4832705da8 (http://localhost:8080/pkg-opt.wasm:wasm-function[331264]:0x4abf78b)
    at ensogl_core::system::gpu::data::uniform::UniformScopeData::add_or_panic::{{closure}}::ha72c316328e4f8eb (http://localhost:8080/pkg-opt.wasm:wasm-function[77737]:0x2ba3221)
    at ensogl_core::system::gpu::data::uniform::UniformScopeData::add_or_else::h0c5b2953c1882f91 (http://localhost:8080/pkg-opt.wasm:wasm-function[15677]:0x174bcb1)
    at ensogl_core::system::gpu::data::uniform::UniformScopeData::add_or_panic::hcc7eba9c14425eaf (http://localhost:8080/pkg-opt.wasm:wasm-function[409463]:0x4d5ab8f)
    at ensogl_core::system::gpu::data::uniform::UniformScope::add_or_panic::hf453f90f6802d785 (http://localhost:8080/pkg-opt.wasm:wasm-function[150430]:0x390f567)
    at ensogl_core::display::scene::Uniforms::new::h59fc2072836da50b (http://localhost:8080/pkg-opt.wasm:wasm-function[282253]:0x478b577)
    at ensogl_core::display::scene::SceneData::new::h5328bada910d449c (http://localhost:8080/pkg-opt.wasm:wasm-function[630]:0x370100)
    at ensogl_core::display::scene::Scene::new::h40cb2291ddd90238 (http://localhost:8080/pkg-opt.wasm:wasm-function[207530]:0x407a428)
    at ensogl_core::display::world::WorldData::new::h875bc6c1f19ed8fe (http://localhost:8080/pkg-opt.wasm:wasm-function[3658]:0xc15100)
    at ensogl_core::display::world::WorldDataWithLoop::new::h552b8d74195dd502 (http://localhost:8080/pkg-opt.wasm:wasm-function[9656]:0x12e70b5)
    at <ensogl_core::display::world::WorldDataWithLoop as core::default::Default>::default::h86b8125299b27e38 (http://localhost:8080/pkg-opt.wasm:wasm-function[500004]:0x4e9333a)
    at <alloc::rc::Rc<T> as core::default::Default>::default::hab58fe62f5bddf7c (http://localhost:8080/pkg-opt.wasm:wasm-function[274131]:0x46debb4)
    at <ensogl_core::display::world::World as core::default::Default>::default::hc768f5c078695f49 (http://localhost:8080/pkg-opt.wasm:wasm-function[318978]:0x4a093bd)
    at ensogl_core::display::world::World::new::heb7fac4deb20b2d0 (http://localhost:8080/pkg-opt.wasm:wasm-function[472609]:0x4e4f87d)
    at ensogl_core::application::Application::new::h135db1c76725e3e3 (http://localhost:8080/pkg-opt.wasm:wasm-function[4652]:0xd9c311)
    at enso_gui::ide::initializer::Initializer::start::{{closure}}::h6e7510035cbee796 (http://localhost:8080/pkg-opt.wasm:wasm-function[470]:0x26a563)
    at enso_gui::entry_point_ide::{{closure}}::hf1843338711a27a9 (http://localhost:8080/pkg-opt.wasm:wasm-function[9576]:0x12d543e)
    at <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::ha1b38156f418dd01 (http://localhost:8080/pkg-opt.wasm:wasm-function[165857]:0x3b4f682)
    at <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next::h0da2424fc66c1c48 (http://localhost:8080/pkg-opt.wasm:wasm-function[2602]:0xa19be2)
    at futures_util::stream::stream::StreamExt::poll_next_unpin::ha3c2b2627ef49dd5 (http://localhost:8080/pkg-opt.wasm:wasm-function[308969]:0x496dd85)
    at futures_executor::local_pool::LocalPool::poll_pool::h3c2f4d48d93bea56 (http://localhost:8080/pkg-opt.wasm:wasm-function[31740]:0x1eb3198)
    at futures_executor::local_pool::LocalPool::run_until_stalled::{{closure}}::hd128c238ae3fe250 (http://localhost:8080/pkg-opt.wasm:wasm-function[113207]:0x32dd255)
    at futures_executor::local_pool::run_executor::{{closure}}::h26b2f4085d736591 (http://localhost:8080/pkg-opt.wasm:wasm-function[40964]:0x21caeb8)
    at std::thread::local::LocalKey<T>::try_with::h7ea2ecff5a6f1abd (http://localhost:8080/pkg-opt.wasm:wasm-function[53671]:0x25b25d2)
    at std::thread::local::LocalKey<T>::with::h243602185cf345af (http://localhost:8080/pkg-opt.wasm:wasm-function[160777]:0x3a9cd85)
    at futures_executor::local_pool::run_executor::h09359ee59d3ba364 (http://localhost:8080/pkg-opt.wasm:wasm-function[158598]:0x3a4d035)
    at futures_executor::local_pool::LocalPool::run_until_stalled::h691ca8daa032327f (http://localhost:8080/pkg-opt.wasm:wasm-function[282540]:0x47914df)
    at enso_executor::web::EventLoopExecutor::runner::{{closure}}::h20019e6a3b21fd47 (http://localhost:8080/pkg-opt.wasm:wasm-function[120331]:0x342aabe)
    at <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::h4384da51a4252ee3 (http://localhost:8080/pkg-opt.wasm:wasm-function[121505]:0x345f25f)
    at ensogl_core::animation::loops::create_callback_wrapper::{{closure}}::h98775fc680fdfe35 (http://localhost:8080/pkg-opt.wasm:wasm-function[157700]:0x3a2c26e)
    at <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::h95ec3f2ab9c36078 (http://localhost:8080/pkg-opt.wasm:wasm-function[282276]:0x478bd57)
    at enso_callback::RegistryModel<F>::run_impl::{{closure}}::h2915a540911f96fd (http://localhost:8080/pkg-opt.wasm:wasm-function[267598]:0x464fc6d)
    at alloc::vec::Vec<T,A>::retain_mut::process_loop::h4841be951cab27bf (http://localhost:8080/pkg-opt.wasm:wasm-function[22582]:0x1af46ca)
    at alloc::vec::Vec<T,A>::retain_mut::h019ce63e191a6c2c (http://localhost:8080/pkg-opt.wasm:wasm-function[57471]:0x26bfcc0)
    at enso_callback::RegistryModel<F>::run_impl::hfb0ade37f11c1a0d (http://localhost:8080/pkg-opt.wasm:wasm-function[5661]:0xee7843)
    at enso_callback::Registry<F>::run_impl::hf14be40f4919d6fb (http://localhost:8080/pkg-opt.wasm:wasm-function[378822]:0x4c9300a)
    at <enso_callback::Registry<dyn core::ops::function::FnMut<(T1,)>+Output = ()> as enso_callback::traits::RegistryRunner1>::run_all::h73ed5eca2a4618f9 (http://localhost:8080/pkg-opt.wasm:wasm-function[319047]:0x4a0a4e0)
    at ensogl_core::animation::loops::on_frame_closure::{{closure}}::{{closure}}::h47f167a566011492 (http://localhost:8080/pkg-opt.wasm:wasm-function[378327]:0x4c8eb32)
    at core::ops::function::FnOnce::call_once::hac335ab895b8611e (http://localhost:8080/pkg-opt.wasm:wasm-function[295957] [...]

2023-03-30 11:55 UTC, somebody1234 commented
looks like it's the same error as the second screenshot

2023-03-30 12:02 UTC, indiv0 commented
Yeah my bad it just looks different because I had more logs in the browser console. It is indeed the same error. FYI this was with a build in a clean environment:

```shell
cd ~/src/enso
~/src/enso/run git-clean
rm -rf ~/src/enso/target
rm -rf ~/src/enso/rust-analyzer-target
rm -rf ~/Library/Application Support/.enso-ci

~/src/enso/run ide build --skip-wasm-opt --wasm-profile=dev --backend-source=release --backend-release=nightly
~/src/enso/dist/ide/mac-arm64/Enso.app/Contents/MacOS/Enso -debug.dev-tools --inspect=5858 -authentication
```

2023-03-30 12:10 UTC, somebody1234 commented
unfortunately i can't test whether it works on linux, the deep link handling is not working.
on that note, is there a reason we aren't using `app.setAsDefaultProtocolClient`?

2023-03-30 12:27 UTC, PabloBuchu commented
> unfortunately i can't test whether it works on linux, the deep link handling is not working. on that note, is there a reason we aren't using `app.setAsDefaultProtocolClient` (on top of what `electron-builder` does for macos and windows) to register the executable as the handler for deep links?

can't you use normal pass/email registration and create account?

2023-03-30 12:34 UTC, somebody1234 commented
yeah, cannot repro :( unless you're supposed to login again every time to try and trigger the error?
restarted several times with `-authentication`, only the first had a login prompt, none of them are producing the error on my end

2023-03-30 12:36 UTC, indiv0 commented
> unfortunately i can't test whether it works on linux, the deep link handling is not working. on that note, is there a reason we aren't using `app.setAsDefaultProtocolClient` (on top of what `electron-builder` does for macos and windows) to register the executable as the handler for deep links?

I must have overlooked this when initially adding the protocol client, as I only have access to a Mac machine. We want deep links to work on all 3 platforms so we should add that for sure.

2023-03-30 12:41 UTC, indiv0 commented
> yeah, cannot repro :( unless you're supposed to login again every time to try and trigger the error? restarted several times with `-authentication`, only the first had a login prompt, none of them are producing the error on my end

@somebody1234 I'm not sure if this is the *minimal* reproduction but here's what seems to work for me consistently:

1. `./run ide build ...`
   - IDE built
2. `./dist/ide/mac-arm64/Enso.app/Contents/MacOS/Enso -debug.dev-tools -authentication`
   - IDE opens
   - Hello page loads (**already signed in from previous start**)
4. Clear all cookies in the `Application` panel of the dev tools (to clear auth state)
5. `Cmd + R` to reload the page
   - Auth page loads (**no more auth cookies**)
7. Click "Login in with google", complete login
   - Get redirected back to app via deep link
   - Hello page loads
   - **Error occurs here**

2023-03-30 13:04 UTC, somebody1234 commented
can repro now... not sure how to even begin debugging this though.
looking at the stack trace, the event loop and panic handler stuff seem irrelevant, so here are the less irrelevant parts:
```rs
    at ensogl_core::system::gpu::data::uniform::UniformScope::add_or_panic
      (lib/rust/ensogl/core/src/system/gpu/data/uniform.rs:78:13)
    at ensogl_core::display::world::WorldData::new
      (lib/rust/ensogl/core/src/display/world.rs:418???)
    at ensogl_core::display::world::WorldDataWithLoop::new
      (lib/rust/ensogl/core/src/display/world.rs:330)
    at ensogl_core::display::world::World::new
      (lib/rust/ensogl/core/src/display/world.rs:247)
    at ensogl_core::application::Application::new
      (lib/rust/ensogl/core/src/application.rs:88)
    ```
out of these most of them seem to be constructors, which isn't very helpful
even more confusing, `UniformScope::add_or_panic` isn't even called directly in `WorldData::new`, and `world::Uniforms` doesn't even have `pixel_ratio`

2023-03-30 13:20 UTC, indiv0 commented
Yeah not sure how to debug this either. FWIW I was able to reproduce this on `develop` just now so it's not related to this PR. I might try bisecting.

2023-03-30 13:55 UTC, indiv0 commented
@wdanilo any thoughts on what could be causing the panic described above? Perhaps it's due to resizing on the web page once the auth view is hidden in favour of the IDE view?

2023-03-30 14:17 UTC, PabloBuchu commented
@indiv0 @somebody1234 this error occurs when runtime tries to define already existing `uniforms` in this case `pixel_ratio`. This might be because we call enso main twice.. @indiv0 is this conncted with what you have found in esbuild PR?

2023-03-30 14:26 UTC, somebody1234 commented
calling `enso.main` twice sounds like it could definitely be it, but i believe it's only ever called in `run.js`, which is a top-level script which means it shouldn't be able to run twice...

2023-03-30 14:38 UTC, somebody1234 commented
ah, but it does indeed seem to be happening based on the screenshots on the other PR

2023-03-30 14:48 UTC, somebody1234 commented
assuming `Scene`s getting rendered twice is the cause of the error, it seems like line 1105 here would be the line that throws the `pixel_ratio` error?

https://github.com/enso-org/enso/blob/d89de84988156c12ab82d1afb40cf77d41d80786/lib/rust/ensogl/core/src/display/scene.rs#L1099-L1109

2023-03-30 14:51 UTC, somebody1234 commented
it may be because `index.ts` is running `new app.App()`, but `run.js` is doing `enso.main()`

2023-03-30 14:52 UTC, somebody1234 commented
so i'd assume the fix would be to delete `run.js`? that doesn't explain why this error only happens intermittently though...

2023-03-30 14:56 UTC, indiv0 commented
@PabloBuchu @somebody1234 I think I got it. `appInstance.run()` is running twice as can be seen from the logs, which explains the double `<div id="scene">`.

I **think** this is happening because a React re-render occurs twice, when we're redirected back to the application. My guess is that:
1. First the `SessionProvider` has a `useEffect` which triggers a re-render (because the `authEventListener` fires and calls `refreshSession`),
2. Then the `AuthProvider` has a `useEffect` which triggers a re-render (because the `session` was updated)

TL;DR: hooks are gross and we should find a way to refactor to avoid this double re-render, but this seems to fix it:

```
diff --git a/app/ide-desktop/lib/content/src/index.ts b/app/ide-desktop/lib/content/src/index.ts
index 3fc612a43..1662bdbaf 100644
--- a/app/ide-desktop/lib/content/src/index.ts
+++ b/app/ide-desktop/lib/content/src/index.ts
@@ -153,9 +153,13 @@ class Main {
                      * and one for the desktop. Once these are merged, we can't hardcode the
                      * platform here, and need to detect it from the environment. */
                     const platform = authentication.Platform.desktop
+                    let appInstanceRan = false
                     const onAuthenticated = () => {
                         hideAuth()
-                        void appInstance.run()
+                        if (!appInstanceRan) {
+                            appInstanceRan = true
+                            void appInstance.run()
+                        }
                     }
                     authentication.run(logger, platform, onAuthenticated)
                 } else {
```

We should also enable `React.StrictMode` to force React to render everything 2x in development mode, so that these bugs are easier to catch.

2023-03-30 18:16 UTC, PabloBuchu approved these changes

2023-03-30 18:17 UTC, PabloBuchu commented
@vitvakatu can we kindly ask for one more QA? :) you can enable auth view with `-authentication=true` flag.

@wdanilo when you have time please take a look

2023-03-30 18:43 UTC, vitvakatu commented
I'll do both QA tomorrow morning.

2023-03-31 06:49 UTC, wdanilo commented
> @vitvakatu can we kindly ask for one more QA? :) you can enable auth view with `-authentication=true` flag.
> 
> @wdanilo when you have time please take a look

Hi @PabloBuchu, what do you mean to take a look? Do you mean review or Q/A? If the former, then I'd be happy to do it as soon as Q/A reports its working. If the latter, I'd not be able to do it unfortunately, could someone else do Q/A, please?

2023-03-31 06:56 UTC, PabloBuchu commented
> > @vitvakatu can we kindly ask for one more QA? :) you can enable auth view with `-authentication=true` flag.
> > @wdanilo when you have time please take a look
> 
> Hi @PabloBuchu, what do you mean to take a look? Do you mean review or Q/A? If the former, then I'd be happy to do it as soon as Q/A reports its working. If the latter, I'd not be able to do it unfortunately, could someone else do Q/A, please?

@wdanilo I meant the review, especially temporary workaround for double rendering https://github.com/enso-org/enso/pull/6132/commits/faf1279f670d74e9835645a3f0864d510546ddd7 (we are working in parrallel fo a proper fix on this)  @vitvakatu promised he will do QA todays morning

2023-03-31 06:59 UTC, wdanilo commented
@PabloBuchu regarding this temporary fix I'm not OK with it as it looks like a hack and there is no comment in the code why we are making such a hack + no info when it will be fixed.

2023-03-31 07:22 UTC, sylwiabr commented
Since this is blocking us from testing the dashboard and merging a chain of issues can we create issue for fixing this workaround and schedule it AFTER merging PRs with the dashboard so we will be able to test cloud in IDE ASAP @wdanilo @PabloBuchu ?

2023-03-31 07:23 UTC, wdanilo commented
@sylwiabr this is probably the plan, but this issue needs QA and @vitvakatu is meant to do it today (according ot the messages above).

2023-03-31 08:01 UTC, PabloBuchu commented
@sylwiabr @wdanilo sorry maybe I wasn't clear enough. The bug with double rendering enso scenes are not introduced by this PR (its's related how the react handles its hooks). We added here temporary fix so we can unblock other PRs, but on the same time we are working on fixing that in proper way. I'll add FIXME in the code as indeed its missing

2023-03-31 09:42 UTC, vitvakatu commented
QA Report 🟢 

#### Minor issue

I run IDE with `-authentication`, log in, clear cookies, select View -> Reload (Cmd-R), login again – I see broken styles on the welcome screen. The issue disappears after restarting IDE, so it is only about reloading. Can't reproduce on develop, because in this scenario it simply hangs on the loading spinner after the second login.

#### Login in `watch` runs a different instance of IDE

(probably a minor issue)
When I run `watch` with `-authentication`, after logging in via GitHub, I'm redirected to the application, but to the wrong one (one of the prebuilt packages I installed a long time ago). Watch-managed Electron is still running at that time.
Also reproducible on `develop`, not caused by this PR.

2023-03-31 09:55 UTC, wdanilo approved these changes

2023-03-31 09:55 UTC, wdanilo commented
Perfect, approved, lets merge it :)

2023-03-31 12:49 UTC, merged