Dashboard directory interactivity
enso-org/enso pull request #6279
Opened 2023-04-14 08:51 UTC by somebody1234

### Pull Request Description
Adds modals:
- upload file modal in drive bar
- context menus
- forms to create files
- drop to upload
- adds permissions display in the "shared with" column with placeholder user avatar

### Screenshots
![image](https://user-images.githubusercontent.com/4046547/231994091-1efd2ce1-2b08-4e0f-9b3f-0625b814d974.png)
![image](https://user-images.githubusercontent.com/4046547/231994125-521f5ae5-43cd-47f9-8506-b7c298c4ae07.png)
![image](https://user-images.githubusercontent.com/4046547/231994249-2a5929c2-0d69-457c-8251-31669f5d07a6.png)
![image](https://user-images.githubusercontent.com/4046547/231994415-80971fc7-10d0-42d5-8848-c504e9fdd034.png)

### Important Notes
N/A

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-04-14 09:03 UTC, somebody1234 commented
oh no... i'll need to clean up the diffs a bit

2023-04-15 07:34 UTC, PabloBuchu commented
@somebody1234 
- please fix merge conflicts
- clicking on `All` or `Docs` blews up the whole dashboard
- Is it possible to right mouse click outside the table element to not open the custom context menu but behaves as default and open normal system menu?

2023-04-18 10:57 UTC, wdanilo commented
It's amazing that this PR has screenshots, but the screenshots are not described. For example, I do not understand what this screenshot shows:


![](https://user-images.githubusercontent.com/4046547/231994091-1efd2ce1-2b08-4e0f-9b3f-0625b814d974.png)

I'd be thankful for explanation of when it shows on the user screen.

2023-04-19 09:54 UTC, PabloBuchu commented
@somebody1234 I see that `+` button next to the projects uses cloud API regardless the desktop/cloud flag. It should behave like in this PR https://github.com/enso-org/enso/pull/6071 later once we introduce the mode cloud/local switcher it should respect that also 

For now when running in electron it should use `createProject` from ProjectManger

2023-04-19 09:56 UTC, PabloBuchu requested changes
see the comments when running in electron

2023-04-19 09:59 UTC, somebody1234 commented
@PabloBuchu because the current implementation in that PR creates an alternative backend, everything should work with little to no changes after that PR is merged in. the project manager doesnt expose endpoints for the other asset types though, so i'm not sure what should be done - maybe either hide them completely, or change the message to say it's not yet supported for local projects, or just return an empty array

2023-04-19 10:48 UTC, somebody1234 commented
as for the assets not being shown, it's because the desktop IDE only supports the local backend, not the cloud backend in this PR.
this should already be fixed in the cloud/desktop switcher

2023-04-19 10:53 UTC, somebody1234 commented
oh actually there's no way to detect whether something is supported other than explicitly checking `backendPlatform`

2023-04-19 11:18 UTC, PabloBuchu commented
@somebody1234 lets hide Directories/Files/Secrets when opened in Electron app and in desktop mode. It still should be visible in electron when user uses cloud thou

2023-04-24 12:49 UTC, wdanilo approved these changes

2023-04-24 15:49 UTC, PabloBuchu commented
@somebody1234 can we hide folders/secrets/files while using electron? then would love to merge it

2023-04-24 16:07 UTC, somebody1234 commented
@PabloBuchu this will be fixed in #6308 - but I guess it doesn't hurt do implement it here as well

2023-04-24 16:15 UTC, somebody1234 commented
@PabloBuchu fix has been pushed

2023-04-25 07:50 UTC, PabloBuchu commented
@somebody1234 the https://github.com/enso-org/enso/pull/6071 was merged so I guess we need to merge and integrate new project templates here before merging

2023-04-26 07:18 UTC, PabloBuchu commented
@somebody1234 when I click on new project or any template I can see in logs that project manager successfully creates the project but nothing is being added to the table. An item shows up after the reload.. we need to fix that

2023-04-26 08:02 UTC, somebody1234 commented
1. committed a potential fix but could not test because of issues with backend
2. should be fixed

2023-04-26 08:33 UTC, PabloBuchu approved these changes

2023-04-26 08:36 UTC, somebody1234 commented
(i've just committed a commit to hide the placeholder data, because i figured it doesn't really matter where it's done, and it's probably not worth its own PR - especially since this one is already changing so much)

2023-04-26 09:52 UTC, merged