Rollback event handling changes for the mouse
enso-org/enso pull request #6396
Opened 2023-04-24 13:22 UTC by vitvakatu

### Pull Request Description

Fixes #6385 

Partial rollback of #6364 

It turns out that preventing default for mouse events is a bad idea in general. It shouldn't affect other fixed bugs because (afaik) all of them were caused by keyboard events.

We're still preventing default for keyboard events.

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-04-24 13:25 UTC, wdanilo requested changes
BTH I don't like having preventDefault in so many places. Maybe they are needed, but every occurrence needs a documentation why it's there and what it is doing. Even better would be to find a single place to prevent them instead of so many.

2023-04-24 13:56 UTC, vitvakatu commented
> BTH I don't like having preventDefault in so many places. Maybe they are needed, but every occurrence needs a documentation why it's there and what it is doing. Even better would be to find a single place to prevent them instead of so many.

1. This is just a partial revert of the previous PR. I didn't write a single line of code myself.
2. There are four places with `prevent_default`, one of them is documented, and others are duplicated because we have separate event handlers for different kinds of events (on_up, on_down, on_leave).

I will see if I can improve this code, but I'm not going to refactor the whole navigator for that.

2023-04-25 09:29 UTC, vitvakatu commented
> There are four places with prevent_default, one of them is documented, and others are duplicated because we have separate event handlers for different kinds of events (on_up, on_down, on_leave).

That's interesting, it looks like most of the places with `prevent_default()` are now unnecessary, the navigator works perfectly fine without this code.

2023-04-25 13:58 UTC, wdanilo approved these changes

2023-04-26 09:05 UTC, farmaazon commented
## QA: Issue spotted:

While the mouse wheel works in documentation panel works, scrolling by grabbing the scroll bar still does not.

2023-04-26 12:26 UTC, vitvakatu commented
> While the mouse wheel works in documentation panel works, scrolling by grabbing the scroll bar still does not.

This is tracked in https://github.com/enso-org/enso/issues/5726, the issue was there before this PR

2023-04-26 12:26 UTC, merged