add remoteLog function for gathering gui logs
enso-org/enso pull request #6582
Opened 2023-05-05 13:29 UTC by PabloBuchu

### Pull Request Description

Example implementation for `remoteLog` function. It uses JWT `accessToken` obtained by the authorization module to sign requests send to `/logs` endpoint of currently used environment.

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-06-26 13:24 UTC, wdanilo requested changes

2023-06-26 13:24 UTC, wdanilo commented on lib/rust/ensogl/pack/js/src/runner/index.ts
> +    accessToken: string | null = null
`App.accessToken` does not explain what it is for. Also, I'm not sure if EnsoGL Pack should have a notion of an access token. It is meant to be like a web-pack replacement, which allows shipping any EnsoGL Apps easily. So this is probably not the right place to add such things.

2023-06-26 13:24 UTC, wdanilo commented on lib/rust/ensogl/pack/js/src/runner/index.ts
>      }
Hmmmm, EnsoGL Pack has a logger, and you can connect any backend to it, including remote logging. For example @mwu-tow connected a file logger to it. I dont think remote logging should be part of EnsoGL Pack.

2023-07-03 22:14 UTC, wdanilo approved these changes

2023-07-03 22:14 UTC, wdanilo commented on app/ide-desktop/lib/content/src/remoteLog.ts
> +    }
sections missing

2023-07-10 12:59 UTC, xvcgreg commented
@mwu-tow What's the delay here about?

2023-07-10 13:13 UTC, mwu-tow commented
Waiting for the cloud team to test. cc @indiv0

2023-07-11 06:52 UTC, PabloBuchu commented
I'll QA this one today

2023-07-11 09:32 UTC, PabloBuchu commented
@mwu-tow how could we add any project identifier to metadata? `projectName` or `projectUuid`?

2023-07-11 09:46 UTC, PabloBuchu commented
Looks good, logs are being pushed properly. I added small improvement for now on backend to associate user email with every entry. Also created issue for improving the log quality with currently opened project https://github.com/enso-org/cloud-v2/issues/537 I think it won't be trivial but we need that also

2023-07-12 10:22 UTC, merged