Moving construction of IR into runtime parser project
enso-org/enso pull request #7096
Opened 2023-06-21 15:16 UTC by JaroslavTulach

### Pull Request Description

Moving and shuffling around to isolate construction of `IR` from the rest of the `runtime` project.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- All code has been tested:
  - [ ] Unit tests have been written where possible and continue to pass

2023-06-21 15:23 UTC, JaroslavTulach commented on engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
> +    val scopeIds = Seq()
TBD: We will need to do something with this...

2023-06-21 16:03 UTC, radeusgd approved these changes
So great that the parser gets a separate module, this looks so much cleaner 🎉

2023-06-21 16:03 UTC, radeusgd commented on engine/runtime-parser/src/main/java/org/enso/compiler/core/ConstantsNames.java
> +}
Please make sure that all files contain a newline at EOF, we try to keep this convention I think.

2023-06-21 16:05 UTC, radeusgd commented
Note that you may need to run `gatherLicenses` - while the dependencies did not change, the internal structure of dependencies has changed - so the hash that is used to verify the dependency structure may need to be updated (but no other action should be needed if dependencies are not moved around).

2023-06-21 17:20 UTC, Akirathan approved these changes

2023-06-21 18:55 UTC, hubertp requested changes
I'm not a fan of all of those `Any` instances and I think this can be removed by even deeper reorganization. This might take a while though. Also currently the project does not compiler in `ChangesetBuilder`

2023-06-22 06:56 UTC, hubertp reviewed
@JaroslavTulach Added some changes that addressed my concerns. Let me know if this is fine with you.

2023-06-22 14:21 UTC, hubertp approved these changes

2023-06-22 14:40 UTC, Akirathan approved these changes
I like that `EnsoCompiler` is renamed to `EnsoParser`. Finally, there won't be both `EnsoCompiler` and `Compiler`.

2023-06-23 05:38 UTC, JaroslavTulach commented on engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/ProcessingPass.scala
> +    type Compiler <: CompilerStub
Interesting. Thank you Hubert.

2023-06-23 05:40 UTC, JaroslavTulach commented on engine/runtime/src/main/scala/org/enso/compiler/pass/IRPass.scala
> -    def prepareForSerialization(compiler: Compiler): Metadata
By defining `type Compiler` we no longer need to override these methods. That's great.

2023-06-23 13:29 UTC, GregoryTravis approved these changes

2023-06-23 14:15 UTC, JaroslavTulach commented on engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
> +    val scopeIds = Seq()
Metadata parser is back since [b6513fb](https://github.com/enso-org/enso/pull/7096/commits/b6513fb8ceae28846e33961bab263226ceaea382)

2023-06-23 14:16 UTC, JaroslavTulach commented on engine/runtime-parser/src/main/java/org/enso/compiler/core/ConstantsNames.java
> +}
There is an empty 9th line.

2023-06-23 14:17 UTC, JaroslavTulach commented on engine/runtime-parser/src/main/java/org/enso/compiler/core/ConstantsNames.java
> +}
I see an empty 9th line: 
![obrazek](https://github.com/enso-org/enso/assets/26887752/e9332b41-c90f-4795-ae28-fea9ebaae2d0)

2023-06-23 17:18 UTC, radeusgd commented on engine/runtime-parser/src/main/java/org/enso/compiler/core/ConstantsNames.java
> +}
![image](https://github.com/enso-org/enso/assets/1436948/76d76486-ea58-4bb1-b765-881c5fc5e146)

GitHub shows that the newline is missing (see the red 'stop sign' at the end). 

It is indeed weird that your editor shows the newline if it seems to be missing in git. Could it be some misconfiguration?

2023-06-24 04:34 UTC, merged

2023-06-24 06:47 UTC, JaroslavTulach commented on engine/runtime-parser/src/main/java/org/enso/compiler/core/ConstantsNames.java
> +}
Will be addressed by https://github.com/enso-org/enso/pull/7115/commits/ef9ee738fe729aeb4126514098d01dd60ac3e35c