Fix GraalVM distribution download on MacOS
enso-org/enso pull request #7364
Opened 2023-07-21 06:43 UTC by Akirathan

- Fix MacOS GraalVM release download
- Fix versioning in sbt/buildGraalDistribution

### Pull Request Description

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-07-21 07:13 UTC, JaroslavTulach approved these changes
I am surprised we haven't seen some failures before this fix.

2023-07-21 07:20 UTC, radeusgd approved these changes

2023-07-21 07:25 UTC, Akirathan commented
> I am surprised we haven't seen some failures before this fix.

I should have asked for QA on MacOS. I have only asked for QA on Windows. That is why I have not spotted this error. Until this is solved, I believe that also nightly builds for MacOS will be failing.

2023-07-21 12:08 UTC, 4e6 approved these changes

2023-07-21 12:45 UTC, mwu-tow requested changes
This breaks build in another place, see the run results:
```
/Users/runner/work/enso/enso/built-distribution/enso-engine-2023.2.1-dev-macos-amd64/enso-2023.2.1-dev/bin/enso: No such file or directory
```

2023-07-21 15:50 UTC, Akirathan commented
> This breaks build in another place, see the run results:
> 
> ```
> /Users/runner/work/enso/enso/built-distribution/enso-engine-2023.2.1-dev-macos-amd64/enso-2023.2.1-dev/bin/enso: No such file or directory
> ```

I think I have just discovered the problems with the IDE building. It seems that I have accidentally broken `./run backend build` and `./run ide build`, both for Linux and Mac. How is it possible that it passed all the tests? Do we not do `./run ide build` on the CI tests?

2023-07-23 09:20 UTC, mwu-tow approved these changes

2023-07-23 09:21 UTC, merged