Parser TS bindings
enso-org/enso pull request #7881
Opened 2023-09-24 13:53 UTC by kazcw

### Pull Request Description

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-09-29 06:41 UTC, farmaazon commented
> I have tested the generated code in isolation, but cannot commit tests as we are not currently able to load WASM modules when running in vitest.

@kazcw I have very similar problem, but also have something like solution:
```ts
if (amIInTestMode()) {
  const fs = await import('node:fs/promises')
  const buffer = await fs.readFile('./rust-ffi/pkg/rust_ffi_bg.wasm')
  await init(buffer)
} else {
  await init()
}
```
(in place of simple `await init()` on the top of `ffi.ts`).
Where `amIInTestMode` should check if we're running in browser or in node. I haven't implemented it myself yet, as haven't decided [which way of detecting node is the best for our case](https://stackoverflow.com/questions/4224606/how-to-check-whether-a-script-is-running-under-node-js)

But you can just put if (true) and make tests on separate branch, once my current PR will fix the problem properly you can also make PR for parser tests.

2023-09-29 08:32 UTC, farmaazon commented on app/gui2/src/util/ffi.ts
> +
Please add TODO explaining that (and possibly when) we plan to remove old AST and rename parseEnso2 and Ast2 to normal parseEnso and Ast.

2023-09-29 08:32 UTC, farmaazon commented on app/gui2/src/util/parserSupport.ts
> +}
I don't understand this class. Could you add a documentation?

2023-09-29 08:32 UTC, farmaazon commented on app/gui2/src/util/parserSupport.ts
> +export type Result<T, E> = { Ok: T } | { Err: E }
You may check out the module I created on my branch: https://github.com/enso-org/enso/blob/wip/farmaazon/loading-suggestion-db/app/gui2/src/util/result.ts it has some additional useful stuff.

2023-09-29 08:32 UTC, farmaazon commented on lib/rust/parser/src/format.rs
> +// FIXME: WASM test required.
When do we plan to fix this FIXME? If not immediately, then could you create an issue for it, and link it here?

2023-09-29 08:32 UTC, farmaazon commented on lib/rust/parser/src/format.rs
> +//! moving each boxed object once.
Maybe it is obvious, but I would add a note why we need to serialize boxes this way: w want to serialize recursive structures.

BTW, I'm surprised there is no ready crate for such scenario. Maybe we should make it a separate crate and publish it?

2023-09-29 08:32 UTC, farmaazon commented on lib/rust/parser/schema/src/lib.rs
> +    Schema { types }
This last part is obscure a bit, it is hard to guess what role it plays.

You can add comments as in the sections before, but there's a better approach: splitting it into a set of well-named functions. You may create a "Builder" structure with all mutable variables here as fields, and make each block a method of it. And `compute_size` could be a method of such structure as well.

2023-09-29 08:32 UTC, farmaazon commented on app/gui2/parser-codegen/src/codegen.ts
> +}
What are the values of this map?

2023-09-29 08:32 UTC, farmaazon commented on app/gui2/parser-codegen/src/codegen.ts
> +}
Isn't `TypeGraph` a part of `Schema`?

2023-09-29 08:32 UTC, farmaazon commented on app/gui2/parser-codegen/src/codegen.ts
> +): (readOk: ExpressionTransformer, readErr: ExpressionTransformer) => ExpressionTransformer {
What `2` means here? Please rename.

2023-09-29 08:32 UTC, farmaazon commented on app/gui2/parser-codegen/src/codegen.ts
> +): (readElement: ExpressionTransformer) => ExpressionTransformer {
Could you add a short description here, what exactly this function returns? What logically the returned transformer accepts and what produces?

2023-10-02 13:39 UTC, kazcw commented on lib/rust/parser/src/format.rs
> +// FIXME: WASM test required.
Fixed

2023-10-04 08:03 UTC, farmaazon requested changes
The parser js API should have much more automatic tests. The documentation also should be improved, but it's not a blocker for merging if it would take too much time.

2023-10-04 08:03 UTC, farmaazon commented on app/gui2/src/util/ffi.ts
> +}
Please add more tests for cases like operator application, block (operator) application, application with default argument, erroneous AST and possibly more. This is a core part of almost every operation we do, and I'd like to be fairy sure it works for basic scenarios. The tests may be in a separate file (we already have some in `__tests__` directory).

2023-10-04 08:03 UTC, farmaazon commented on lib/rust/parser/schema/src/main.rs
> +//! AST representations and (de)serialization.
```suggestion
//! Generate a schema representing `enso-parser`'s AST types. This schema can be used to generate
//! AST representations in other languages and (de)serialization.
```

2023-10-04 08:03 UTC, farmaazon commented on lib/rust/parser/src/format.rs
> +//! moving each boxed object once.
> Maybe it is obvious, but I would add a note why we need to serialize boxes this way: w want to serialize recursive structures.

Well, the description is needed even more, given that what I wrote before is actually wrong :) We do such boxing to have structures equal in size, what helps to implement "lazy deserialization" in js.

2023-10-04 08:03 UTC, farmaazon commented on app/gui2/parser-codegen/src/codegen.ts
> +}
I would add simple tests for those functions.

2023-10-04 08:03 UTC, farmaazon commented on app/gui2/parser-codegen/src/codegen.ts
This file is quite big. Can we split it into submodules? For example:
* One with helper functions (like toPascal) with simple inline tests for those
* One for code generating functions (also with tests if possible)
* Optionally one for schema types 
* And one for "Main" code.

Also, I miss a description of what code this actually produces, and why we're doing it this way - after all, this is not a simple TS structures representing AST code.

2023-10-04 08:03 UTC, farmaazon commented on app/gui2/parser-codegen/src/codegen.ts
> + */
An example would make it greatly easier to understand this function.

2023-10-04 08:03 UTC, farmaazon commented on lib/rust/parser/src/format.rs
> +    }
Add a test case for serializing some simple structure, and also simple but with boxed fields structure (checking the generated binary content).

2023-10-04 09:29 UTC, farmaazon commented
For example: This test created on my branch derived from this one is raising an exception:
```ts
  test('TryParseSmthing', () => {
    const smthing = 'Data.read file="name"'
    const parsed = parseEnso2(smthing)
    Array.from(parsed.statements)[0].expression.name.isTypeOrConstructor
  })
```

2023-10-04 12:49 UTC, Frizi commented on app/gui2/parser-codegen/src/codegen.ts
> +}
We should really use a dependency for this kind of stuff. Having to write and test it ourselves is really pointless. There is a good package for that: https://www.npmjs.com/package/change-case

2023-10-11 08:41 UTC, farmaazon approved these changes

2023-10-11 12:58 UTC, Frizi approved these changes

2023-10-11 13:04 UTC, merged