Let logging to file respect log level
enso-org/enso pull request #8264
Opened 2023-11-08 23:35 UTC by hubertp

### Pull Request Description

This change fixes a regression introduced in #7918, which prevented the execution from setting the right log level either via env var or parameter.

Now passing either of the options returns logs of the expected level in the log file:
- `ENSO_LOG_TO_FILE_LOG_LEVEL = trace`
- ... `-vv` ...

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

~~- [ ] The documentation has been updated, if necessary.~~
~~- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
~~- [ ] Unit tests have been written where possible.~~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-11-09 10:19 UTC, Akirathan requested changes
When I use
```diff
diff --git a/engine/language-server/src/main/resources/application.conf b/engine/language-server/src/main/resources/application.conf
index c2d9e1ded..eb6ac846c 100644
--- a/engine/language-server/src/main/resources/application.conf
+++ b/engine/language-server/src/main/resources/application.conf
@@ -56,7 +56,7 @@ logging-service {
   default-appender = socket
   default-appender = ${?ENSO_APPENDER_DEFAULT}
   log-to-file {
-    enable = false
+    enable = true
     enable = ${?ENSO_LOG_TO_FILE}
     log-level = debug
     log-level = ${?ENSO_LOG_TO_FILE_LOG_LEVEL}
```
I still have 5 GBs of output in my stdout, even though the default log level to console should be INFO. What is the purpose of `log-to-file.enable` property then?

2023-11-09 10:19 UTC, Akirathan commented on engine/language-server/src/main/resources/application.conf
> +    org.enso.languageserver.protocol.json.JsonConnectionController = debug
Nice to see that this is uncommented by default.

2023-11-09 17:28 UTC, hubertp commented on engine/language-server/src/main/resources/application.conf
> +    org.enso.languageserver.protocol.json.JsonConnectionController = debug
Yes, I got fed up with it. In `trace` you can't see anything because of it.

2023-11-10 11:28 UTC, hubertp commented
> When I use
> ... 
> I still have 5 GBs of output in my stdout, even though the default log level to console should be INFO. What is the purpose of ?`log-to-file.enable` property then?

It's a problem unrelated to the fact what this PR is fixing but I've been thinking how to best tackle this anyway.

As noted internally setting log-to-file for language server that is being started by project-manager makes little sense when using socket appender. It probably would make sense if language server was started separately. For now, just hardcoded the fact that language server should always reset the `LoggerContext` thus ensuring console is not flooded by logs. I would only spend more time on this if there is a real use-case to support it.

2023-11-10 11:42 UTC, Akirathan approved these changes

2023-11-14 11:58 UTC, 4e6 approved these changes

2023-11-14 11:59 UTC, merged