enso-8194 Copy and pasting a single node
enso-org/enso pull request #8298
Opened 2023-11-14 11:47 UTC by MichaelMauderer

### Pull Request Description
Implements  #8194

[Peek 2023-11-13 14-15.webm](https://github.com/enso-org/enso/assets/1428930/22882487-7288-4eb7-af08-6539060b4967)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-11-14 12:58 UTC, vitvakatu commented
Please note that this implementation stores nodes in a custom JSON-based format with `text/plain` MIME-type, which means any external program will receive a bunch of unnecessary metadata when pasting.
The implementation in the old GUI was using two payloads: 
1. `text/plain` contains only the code. It is used when pasting in other programs.
2. `web application/enso` containing our custom format with metadata.

This was a feature specifically requested on the demo.

Also, we’re not handling node positions here – the node is always placed under the cursor, even if another node is already there. We don‘t have the necessary API for this issue yet, but it must be remembered.

2023-11-15 09:54 UTC, Frizi requested changes
Please address the mime type issues pointed out by @vitvakatu.

2023-11-15 09:54 UTC, Frizi commented on app/gui2/src/components/GraphEditor.vue
> +  const copiedNode: CopiedNode = { expression: content, metadata }
The stored format assumes a single node. It is fine to support copying only one for now, but let's make some room for easily extending it later, such as making the top-level object contain an array of nodes already (e.g. `{ nodes: CopiedNode[] }`).

2023-11-15 14:46 UTC, Frizi approved these changes

2023-11-16 09:30 UTC, somebody1234 commented
@MichaelMauderer just a heads up, this is ready to merge (all required checks are passing too) but there are new merge conflicts

2023-11-17 03:57 UTC, merged