Parse inline function signatures
enso-org/enso pull request #8470
Opened 2023-12-06 05:44 UTC by kazcw

### Pull Request Description

Implements #6166.

### Important Notes

- More consistent handling of `default` arguments. `default` is a valid identifier, and only has special meaning when it isn't bound in scope. Since distinguishing the builtin `default` from an identifier called `default` cannot be done until alias analysis has been performed, `default` is now represented in the AST as a regular identifier.
- `TreeToIr`: Remove `insideTypeAscription`. It was only used for bug-for-bug compatibility with the old parser during the transition.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-12-06 08:12 UTC, JaroslavTulach requested changes
This PR claims to fix #6166. It seems to do so, but it also does something with `default`. That doesn't seem to be in scope of #6166...

> More consistent handling of default arguments. default is a valid identifier, and only has special meaning when it isn't bound in scope. Since distinguishing the builtin default from an identifier called default cannot be done until alias analysis has been performed, default is now represented in the AST as a regular identifier.

... OK, can we see how the `default` behaves in the runtime? For example by modifying the `ExecCompilerTest`?

2023-12-06 08:12 UTC, JaroslavTulach commented on engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
> +          // TODO: Make use of return type declaration.
Is this (follow up?) work tracked somewhere?

2023-12-06 08:12 UTC, JaroslavTulach commented on app/gui2/src/util/ast/__tests__/aliasAnalysis.test.ts
> +    «3,default» = 1
What's the expected meaning of
```
3,default = 1
```
Is it even a valid syntax in Enso? I don't think we can execute anything like that.

2023-12-06 08:12 UTC, JaroslavTulach commented on lib/rust/parser/debug/tests/parse.rs
> +    test!("number -> Integer = 23",
Can you also add such a test to [ExecCompilerTest](https://github.com/enso-org/enso/blob/c814e5efbce65461832e0827e0bb74b7f27989e4/engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java#L157)?

2023-12-06 14:53 UTC, kazcw commented on engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
> +          // TODO: Make use of return type declaration.
#8240

2023-12-06 14:56 UTC, kazcw commented on app/gui2/src/util/ast/__tests__/aliasAnalysis.test.ts
> +    «3,default» = 1
The `3,` is part of the test syntax. The LHS is just the identifier `default`.

2023-12-06 20:01 UTC, kazcw commented
@JaroslavTulach I added tests for `default`. One is `@Ignore`d for now, because it seems `default` is not implemented yet. Opened a compiler bug: #8480.

2023-12-07 12:44 UTC, JaroslavTulach approved these changes

2023-12-08 11:55 UTC, radeusgd commented on engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
> +  }
I think we should also get a test when there is more than 0 arguments 🙂 

I'd be happy to add a test case, may I push to your branch?

2023-12-08 11:56 UTC, radeusgd approved these changes

2023-12-08 13:53 UTC, radeusgd commented on engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
> +  }
I'd like to add a following patch:
```diff
Subject: [PATCH] add 2 more compiler test cases
---
Index: engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java b/engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
--- a/engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java	(revision 45ed77d513735bce59e2c8739a55a38560a69ccb)
+++ b/engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java	(revision 7273a5c43575d2e913caa18f9a4edc071d6df135)
@@ -199,6 +199,29 @@
     assertEquals("10 % 3 is one", 1, result.asInt());
   }
 
+  @Test
+  public void inlineReturnSignature() throws Exception {
+    var module = ctx.eval("enso", """
+    foo (x : Integer) (y : Integer) -> Integer = 10*x + y
+    """);
+    var foo = module.invokeMember("eval_expression", "foo");
+    assertTrue("foo a function", foo.canExecute());
+    assertEquals(45, foo.execute(4, 5).asInt());
+  }
+
+  @Test
+  public void inlineReturnSignatureOnMemberMethod() throws Exception {
+    var module = ctx.eval("enso", """
+    type My_Type
+        Value x
+        
+        foo self (y : Integer) z -> Integer = 100*z + 10*y + self.x
+    """);
+    var instance = module.invokeMember("eval_expression", "My_Type.Value 1");
+    var result = instance.invokeMember("foo", 2, 3);
+    assertEquals(321, result.asInt());
+  }
+
   @Test
   public void inlineReturnSignatureWithoutArguments() throws Exception {
     var module = ctx.eval("enso", """
```
Tests are passing with it.

@kazcw  May I push it to this PR?

2023-12-08 14:43 UTC, kazcw commented on engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
> +  }
@radeusgd Sure.

2023-12-12 12:07 UTC, Frizi approved these changes

2023-12-12 14:48 UTC, merged

2023-12-15 06:53 UTC, JaroslavTulach commented on engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
> +          // TODO(#8240): Make use of return type declaration.
Continuations:
- #8240 
- #8502