Cleanup `@/util` folder
enso-org/enso pull request #8501
Opened 2023-12-08 11:59 UTC by somebody1234

### Pull Request Description
- Partially addresses #8228
  - Moves several files into `@/util/vue` and `@/util/data`
- Makes imports more consistent:
  - Remove redundant trailing `.ts`
  - Convert *some* imports to use `@/` rather than `./`
    - Ideally it should be all imports other than the ones outside of `src/`, but I can't be sure I've found all of them
  - Merge *some* duplicated imports (caused by one being an `import type`)

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-12-08 13:38 UTC, Frizi requested changes

2023-12-08 13:38 UTC, Frizi commented on app/gui2/src/components/CodeEditor.vue
> +@/util/data/result @/util/data/iterable
There are weird trailing module names everywhere. Probably due to automatic refactor screwing something up. Please check all modified vue files for them, as it is present in almost every one.

2023-12-08 13:38 UTC, Frizi commented on app/gui2/src/stores/visualization/runtimeTypes.ts
> +      else if (isUrlString(s)) return s as URLString
This `s as URLString` cast should no longer be necessary due to the type assertion in `isUrlString` return value.

2023-12-08 13:38 UTC, Frizi commented on app/gui2/src/stores/visualization/runtimeTypes.ts
>        if (iconNames.includes(s)) return s as Icon
maybe this `includes` could also be moved to a `isBuiltinIcon` function, so we don't need the type cast.

2023-12-08 13:38 UTC, Frizi commented on app/gui2/src/util/data/README.md
> +  - `vec2.ts` defines a `Vec2` type representing an arbitrary two-dimensional quantity
I feel like all of those points should rather be a top-level docs in each of those files, instead of listing them in a folder readme. As it is, this file will become inaccurate very quickly. We may have one very high level readme explaining the project folder structure (without listing individual files), but I wouldn't then put a readme in each of those subfolders.

2023-12-08 13:38 UTC, Frizi commented on app/gui2/src/util/vue/README.md
> +- `animation.ts` defines:
Same thing as the other readme file. All of those should be docs for the modules/methods, not a separate file.

2023-12-08 14:07 UTC, somebody1234 commented
I only just noticed `@/composables` in the very last commit - perhaps we could move most of `@/util/vue` to `@/composables` instead?

2023-12-11 14:47 UTC, Frizi approved these changes

2023-12-13 22:27 UTC, merged