Add support for dynamic dropdowns in vector editor
enso-org/enso pull request #8568
Opened 2023-12-18 09:04 UTC by vitvakatu

### Pull Request Description

Closes #8532

Adds support for dynamic dropdowns inside the vector editor, providing default value for new items, and also fixing trivial cases with calls like `Table.get`.

https://github.com/enso-org/enso/assets/6566674/583afc02-f476-4345-94ca-41495d1b3e38

### Important Notes

For now, we pass `dynamicConfig` everywhere manually, which requires a lot of boilerplate in each widget. The obvious solution would be to use `provider` to pass dynamic configuration down the widget graph, but I didn’t have time to implement it yet. We can create a separate task for that, shouldn’t be too hard. @Frizi, you asked about my thoughts on this. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2023-12-18 09:38 UTC, farmaazon requested changes
I see serious flaws in current implementation. And it's still very buggy:
1. If I add node `order_by` and only after realize I miss the list (as the placeholder does not allow making entries yet) and edit node to add `[]` then no dynamic config seems to work in the node:
![image](https://github.com/enso-org/enso/assets/3919101/f1abe80c-49f5-4fe0-9589-021416359b73)

2. In aggregate, the default value works, but Group_By does not make space for column name

![image](https://github.com/enso-org/enso/assets/3919101/aa01560e-3f14-4fc4-afa4-835786718ad9)

3. Picking values in drop-downs inside list editors does not seem to change anything

2023-12-18 09:38 UTC, farmaazon commented on app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
> +    values = widgetConfig.values
It's very patchy. Now every widget must consider if it happens to be inside vector editor. I think the ListEditor should just pass `item_editor` as dynamicConfig of its elements. Similarly, it's the WidgetFunction/Application which should extract the piece of config for every argument.

2023-12-18 09:38 UTC, farmaazon commented on app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
> +    widgetConfig.item_editor.kind === 'Single_Choice'
Why the item_editor must be a `Single_Choice`? I thought the default can be just any value, e.g. number for number slider.

2024-01-03 15:03 UTC, closed without merging

2024-01-03 15:03 UTC, vitvakatu commented
Refactored and included in https://github.com/enso-org/enso/pull/8624