Update icon definitions to new figma export format
enso-org/enso pull request #8860
Opened 2024-01-25 13:24 UTC by Frizi

### Pull Request Description

Related to #8387 

Updated icons file to match the export format of figma plugin.

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2024-01-25 13:52 UTC, farmaazon commented
I tried to test it, but typecheck fails with error:
```
src/components/widgets/PlaceholderWidget.vue:7:6 - error TS2345: Argument of type '{ width: number; height: number; name: "underscore"; }' is not assignable to parameter of type '{ readonly name: Icon | URLString; style?: unknown; class?: unknown; key?: string | number | symbol; ref?: VNodeRef; ref_for?: boolean; ref_key?: string; onVnodeBeforeMount?: VNodeMountHook | VNodeMountHook[]; ... 6 more ...; readonly width?: number; } & Record<...>'.
  Type '{ width: number; height: number; name: "underscore"; }' is not assignable to type '{ readonly name: Icon | URLString; style?: unknown; class?: unknown; key?: string | number | symbol; ref?: VNodeRef; ref_for?: boolean; ref_key?: string; onVnodeBeforeMount?: VNodeMountHook | VNodeMountHook[]; ... 6 more ...; readonly width?: number; }'.
    Types of property 'name' are incompatible.
      Type '"underscore"' is not assignable to type 'Icon | URLString'.

7     <SvgIcon :width="24" :height="16" name="underscore" />
       ~~~~~~~
```
Code wise it's accepted, I just wanted to make sure no important icon disappeared (their visibility is not covered by e2e tests)

2024-01-26 07:28 UTC, farmaazon requested changes
The marketplace icon is broken:

![image](https://github.com/enso-org/enso/assets/3919101/6a0031da-99ec-4e3e-b207-054e113e05d8)

I remember the issue appeared also when I was manually exporting icons. I needed to do some fixes in SVG - you may check out the old icon definition and compare. Let's fix the icon in figma document.

2024-01-29 09:10 UTC, vitvakatu commented
The marketplace icon issue might be using the `mask` tag in the SVG. It is not supported when importing SVGs with `use`, as we do: https://stackoverflow.com/questions/72027981/mask-tag-in-svg-is-ignored-if-used-from-an-external-svg-sprite-file

2024-01-29 14:10 UTC, farmaazon commented
Fixed marketplace icon in PR, but not in figma.

2024-01-29 14:10 UTC, farmaazon approved these changes

2024-02-05 13:15 UTC, Frizi commented
Icons fixed in figma and reexported.

2024-02-05 15:29 UTC, merged