Dropdown widget improvements.
enso-org/enso pull request #9186
Opened 2024-02-26 14:40 UTC by MichaelMauderer

### Pull Request Description

Closes  #8995

[Peek 2024-02-26 14-39.webm](https://github.com/enso-org/enso/assets/1428930/cc3db6a8-7577-4e7a-9ad6-f1b673c577b4)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2024-02-29 13:21 UTC, farmaazon requested changes
The arrow is wrongly moved to WidgetArgumentName; first, the task description says, that it should be under _constructor_ name, not argument name; that is, centered under `AggregateColumn.Group_By`, not under `AggregateColumn.Group_By 'some_name'`

And the WidgetArgumentName is not always displayed; The arguments of nested calls, or list elements now have no arrow, I guess.

2024-02-29 13:21 UTC, farmaazon commented on app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
>  }
I think this function may be removed.

2024-03-01 16:07 UTC, MichaelMauderer commented
Updated without the arrow changes after discussion with @farmaazon. They will be implemented in another task due to the unexpected complexity of the required implementation.

2024-03-04 08:10 UTC, farmaazon approved these changes

2024-03-04 12:54 UTC, merged