Scrollbars
enso-org/enso pull request #9310
Opened 2024-03-07 01:27 UTC by kazcw

### Pull Request Description

Add scrollbars.

https://github.com/enso-org/enso/assets/1047859/83891fa7-c1c8-44ee-9512-9f42fec5cd3b

### Important Notes

- Bounded overscroll is supported: A scrollbar can be pushed past its end by up to its full length, making it easy to get slightly outside the populated area. If you really want to get away, you can do it repeatedly.
- If a scrollbar is as wide as the viewport (i.e. the whole graph fits on the screen in that axis), it hides. It comes back if hovered so you can still drag it to overscroll.
- Implemented the scrollbars from scratch because all available scrollbar components look basically the same (like these) and are simple to draw, but none of them seem to support the kind of overscroll we'd want.
- ScrollBar.vue is a general purpose scrollbar control using client coordinates; SceneScroller.vue hooks it up to the `graphNavigator` and connects it to `graphStore` information, and adds scene-relative panning logic.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2024-03-07 10:05 UTC, AdRiley commented
Looking good! Is it possible to make them thinner?

2024-03-12 14:58 UTC, Frizi requested changes

2024-03-12 14:58 UTC, Frizi commented on app/gui2/src/util/data/vec2.ts
> +    return new Vec2(x, y)
This is not a dot product, since it produces a vector. This appears to be a Hadamard (component-wise) product instead.

2024-03-12 16:14 UTC, Frizi approved these changes

2024-03-12 16:44 UTC, merged