Use predefined zoom levels
enso-org/enso pull request #9585
Opened 2024-04-01 12:45 UTC by vitvakatu

### Pull Request Description

Fixes one subtask of #9354 

https://github.com/enso-org/enso/assets/6566674/3418d31e-2d80-48b2-ba8b-9e000b09cf14

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

2024-04-03 14:29 UTC, kazcw requested changes
Nits:
- The `ScaleRange` argument to `stepZoom` seems redundant given the fixed list.
- `WHEEL_SCALE_RANGE` is now only relevant for gestures, so it could be renamed.
- I don't think the `directedClamp` logic is really doing anything anymore.

2024-04-03 14:41 UTC, kazcw commented
Previously we rounded to a zoom level before stepping. This was because some zoom methods, like OS X pinch-zoom, make it easy to make fine changes to the zoom level. If the user then zooms with a stepwise method like clicking the button, if we advance to the next step without considering how close we might be already, our change to the floating point scale factor could make little or no observable difference.

This might be a matter of opinion, but an action like clicking a zoom button has a clear intent and I think it's odd if the UI doesn't appear to react much.

2024-04-05 10:59 UTC, vitvakatu commented
> I think this change allows some code simplification:

Applied first two, I still think `directedClamp` is useful, because it is used in other places and we have quite a few ways of changing zoom, which potentially could lead to value outside of range. (we even export `zoom` value, so technically anyone can edit it at any time.

I also introduced a small threshold value so that we skip zoom levels which are too close. It can require some more tweaking, but works seemingly fine.

2024-04-05 13:14 UTC, kazcw approved these changes

2024-04-08 11:12 UTC, merged