Track live selection
enso-org/enso pull request #9924
Opened 2024-05-10 23:46 UTC by kazcw

### Pull Request Description

Remove components from the selection when they cease to be present in the displayed graph; when they are removed for this reason, they will be added back to the selection if they are recreated and no intervening selection change has occurred.

Fixes #9903.

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

2024-05-15 09:47 UTC, farmaazon requested changes

2024-05-15 09:47 UTC, farmaazon commented on app/gui2/src/composables/selection.ts
> +    },
We said during refinement, that we should have the `actually selected` field being a `computed` value which filters out `selected` which are not in `graphDb.nodeIdToNode.keys`. The keyset is reactive, so any change affecting our selection would make the computed to recompute.

I prefer the `computed` solution: it's maybe a bit farther from being optimal, but much simpler: wouldn't need to manually inform selection that a node was added/deleted.

2024-05-15 09:47 UTC, farmaazon commented on app/gui2/src/stores/graph/graphDatabase.ts
> +    onNodeDeleted: (id: NodeId) => void,
These are redundant to ReactiveDB's `entryAdded` event (which is available in public)

2024-05-16 08:35 UTC, farmaazon approved these changes

2024-05-16 08:35 UTC, farmaazon commented on app/gui2/shared/util/data/iterable.ts
> +
There is `lib0/iteratorFilter` perhaps we could just reexport it here.

2024-05-16 08:35 UTC, farmaazon commented on app/gui2/src/composables/selection.ts
> +  const rawSelected = shallowReactive(new Set<T>())
`raw` is a bit unclear term, but I cannot think of any other name. At least, a comment explaining what is `rawness` here would help future readers.

2024-05-16 12:29 UTC, kazcw commented on app/gui2/shared/util/data/iterable.ts
> +
That takes an `iterator`, which is less convenient.

2024-05-16 13:24 UTC, merged