Rename Connector to DataLinks
enso-org/enso pull request #9948
Opened 2024-05-14 12:29 UTC by MrFlashAccount

### Pull Request Description

This PR doesn't do anything special, just renames Connector to DataLink. 

### Important Notes

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

2024-05-14 12:31 UTC, somebody1234 approved these changes
CR :white_check_mark:, QA not done (it's late here)

2024-05-17 09:13 UTC, PabloBuchu commented on app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
> +                              dataLinkId: item.item.id,
its `datalinkId` not `dataLinkId`

2024-05-17 09:15 UTC, PabloBuchu requested changes
its Datalink not Data Link so the camel case format is `datalink`

2024-05-17 09:15 UTC, PabloBuchu commented on app/ide-desktop/lib/dashboard/src/services/Backend.ts
> +  dataLink = 'dataLink',
same rename to `datalink`

2024-05-17 09:15 UTC, PabloBuchu commented on app/ide-desktop/lib/dashboard/src/services/Backend.ts
> +  abstract getDataLink(dataLinkId: DataLinkId, title: string | null): Promise<DataLink>
all occurrences of `dataLink` or `dataLinkId` should be renamed to `datalink` or `datalinkId`

2024-05-17 09:15 UTC, PabloBuchu commented on app/ide-desktop/lib/dashboard/src/services/remoteBackendPaths.ts
> +/** Relative HTTP path to the "create data link" endpoint of the Cloud backend API. */
`create datalink`

2024-05-17 10:20 UTC, MrFlashAccount commented
@PabloBuchu renamed, please take a look once again.

@somebody1234 I didn't touch the DataLink schema fields, not sure we can safely touch it

2024-05-17 10:26 UTC, somebody1234 commented
> didn't touch the DataLink schema fields

we don't need to touch the DataLink schema right?
but if it's just the *descriptions* then it should be fine. we definitely don't want to be changing the actual shape otherwise the generated JSON will no longer be valid inputs for libs.

i assume it's safe to rename the variant names as well - libs doesn't appear to depend on the JSON Schema file:
https://github.com/search?q=repo%3Aenso-org%2Fenso+dataLinkSchema&type=code

2024-05-17 10:28 UTC, somebody1234 commented
you should probably update the path in codeowners though (`dataLink` -> `datalink`):
https://github.com/enso-org/enso/blob/a5ca9f9ac22a6a87ab4f9ec13c1ba4a8cbaaed62/.github/CODEOWNERS#L50

2024-05-17 10:49 UTC, MrFlashAccount commented
> you should probably update the path in codeowners though (dataLink -> datalink):

Oh, yeah, thanks for noticing!

2024-05-17 14:04 UTC, GregoryTravis approved these changes

2024-05-17 15:36 UTC, radeusgd approved these changes
We probably need a similar PR renaming the usages in our libs. I was always calling it `Data Link` as I was not aware of any 'official' spelling.

2024-05-20 08:44 UTC, PabloBuchu approved these changes

2024-05-20 08:45 UTC, merged